// Code generated by ent, DO NOT EDIT.

package paymentrecord

import (
	"projecttemp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldUserID, v))
}

// StripeSessionID applies equality check predicate on the "stripe_session_id" field. It's identical to StripeSessionIDEQ.
func StripeSessionID(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldStripeSessionID, v))
}

// StripePaymentIntentID applies equality check predicate on the "stripe_payment_intent_id" field. It's identical to StripePaymentIntentIDEQ.
func StripePaymentIntentID(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldStripePaymentIntentID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldCurrency, v))
}

// ProductType applies equality check predicate on the "product_type" field. It's identical to ProductTypeEQ.
func ProductType(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldProductType, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldDescription, v))
}

// RefundTime applies equality check predicate on the "refund_time" field. It's identical to RefundTimeEQ.
func RefundTime(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldRefundTime, v))
}

// RefundReason applies equality check predicate on the "refund_reason" field. It's identical to RefundReasonEQ.
func RefundReason(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldRefundReason, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldUpdateTime, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldUserID, vs...))
}

// StripeSessionIDEQ applies the EQ predicate on the "stripe_session_id" field.
func StripeSessionIDEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldStripeSessionID, v))
}

// StripeSessionIDNEQ applies the NEQ predicate on the "stripe_session_id" field.
func StripeSessionIDNEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldStripeSessionID, v))
}

// StripeSessionIDIn applies the In predicate on the "stripe_session_id" field.
func StripeSessionIDIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldStripeSessionID, vs...))
}

// StripeSessionIDNotIn applies the NotIn predicate on the "stripe_session_id" field.
func StripeSessionIDNotIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldStripeSessionID, vs...))
}

// StripeSessionIDGT applies the GT predicate on the "stripe_session_id" field.
func StripeSessionIDGT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldStripeSessionID, v))
}

// StripeSessionIDGTE applies the GTE predicate on the "stripe_session_id" field.
func StripeSessionIDGTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldStripeSessionID, v))
}

// StripeSessionIDLT applies the LT predicate on the "stripe_session_id" field.
func StripeSessionIDLT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldStripeSessionID, v))
}

// StripeSessionIDLTE applies the LTE predicate on the "stripe_session_id" field.
func StripeSessionIDLTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldStripeSessionID, v))
}

// StripeSessionIDContains applies the Contains predicate on the "stripe_session_id" field.
func StripeSessionIDContains(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContains(FieldStripeSessionID, v))
}

// StripeSessionIDHasPrefix applies the HasPrefix predicate on the "stripe_session_id" field.
func StripeSessionIDHasPrefix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasPrefix(FieldStripeSessionID, v))
}

// StripeSessionIDHasSuffix applies the HasSuffix predicate on the "stripe_session_id" field.
func StripeSessionIDHasSuffix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasSuffix(FieldStripeSessionID, v))
}

// StripeSessionIDEqualFold applies the EqualFold predicate on the "stripe_session_id" field.
func StripeSessionIDEqualFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEqualFold(FieldStripeSessionID, v))
}

// StripeSessionIDContainsFold applies the ContainsFold predicate on the "stripe_session_id" field.
func StripeSessionIDContainsFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContainsFold(FieldStripeSessionID, v))
}

// StripePaymentIntentIDEQ applies the EQ predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDNEQ applies the NEQ predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDNEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDIn applies the In predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldStripePaymentIntentID, vs...))
}

// StripePaymentIntentIDNotIn applies the NotIn predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDNotIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldStripePaymentIntentID, vs...))
}

// StripePaymentIntentIDGT applies the GT predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDGT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDGTE applies the GTE predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDGTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDLT applies the LT predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDLT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDLTE applies the LTE predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDLTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDContains applies the Contains predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDContains(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContains(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDHasPrefix applies the HasPrefix predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDHasPrefix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasPrefix(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDHasSuffix applies the HasSuffix predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDHasSuffix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasSuffix(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDIsNil applies the IsNil predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDIsNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIsNull(FieldStripePaymentIntentID))
}

// StripePaymentIntentIDNotNil applies the NotNil predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDNotNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotNull(FieldStripePaymentIntentID))
}

// StripePaymentIntentIDEqualFold applies the EqualFold predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDEqualFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEqualFold(FieldStripePaymentIntentID, v))
}

// StripePaymentIntentIDContainsFold applies the ContainsFold predicate on the "stripe_payment_intent_id" field.
func StripePaymentIntentIDContainsFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContainsFold(FieldStripePaymentIntentID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldStatus, vs...))
}

// ProductTypeEQ applies the EQ predicate on the "product_type" field.
func ProductTypeEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldProductType, v))
}

// ProductTypeNEQ applies the NEQ predicate on the "product_type" field.
func ProductTypeNEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldProductType, v))
}

// ProductTypeIn applies the In predicate on the "product_type" field.
func ProductTypeIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldProductType, vs...))
}

// ProductTypeNotIn applies the NotIn predicate on the "product_type" field.
func ProductTypeNotIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldProductType, vs...))
}

// ProductTypeGT applies the GT predicate on the "product_type" field.
func ProductTypeGT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldProductType, v))
}

// ProductTypeGTE applies the GTE predicate on the "product_type" field.
func ProductTypeGTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldProductType, v))
}

// ProductTypeLT applies the LT predicate on the "product_type" field.
func ProductTypeLT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldProductType, v))
}

// ProductTypeLTE applies the LTE predicate on the "product_type" field.
func ProductTypeLTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldProductType, v))
}

// ProductTypeContains applies the Contains predicate on the "product_type" field.
func ProductTypeContains(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContains(FieldProductType, v))
}

// ProductTypeHasPrefix applies the HasPrefix predicate on the "product_type" field.
func ProductTypeHasPrefix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasPrefix(FieldProductType, v))
}

// ProductTypeHasSuffix applies the HasSuffix predicate on the "product_type" field.
func ProductTypeHasSuffix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasSuffix(FieldProductType, v))
}

// ProductTypeEqualFold applies the EqualFold predicate on the "product_type" field.
func ProductTypeEqualFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEqualFold(FieldProductType, v))
}

// ProductTypeContainsFold applies the ContainsFold predicate on the "product_type" field.
func ProductTypeContainsFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContainsFold(FieldProductType, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContainsFold(FieldDescription, v))
}

// RefundTimeEQ applies the EQ predicate on the "refund_time" field.
func RefundTimeEQ(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldRefundTime, v))
}

// RefundTimeNEQ applies the NEQ predicate on the "refund_time" field.
func RefundTimeNEQ(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldRefundTime, v))
}

// RefundTimeIn applies the In predicate on the "refund_time" field.
func RefundTimeIn(vs ...time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldRefundTime, vs...))
}

// RefundTimeNotIn applies the NotIn predicate on the "refund_time" field.
func RefundTimeNotIn(vs ...time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldRefundTime, vs...))
}

// RefundTimeGT applies the GT predicate on the "refund_time" field.
func RefundTimeGT(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldRefundTime, v))
}

// RefundTimeGTE applies the GTE predicate on the "refund_time" field.
func RefundTimeGTE(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldRefundTime, v))
}

// RefundTimeLT applies the LT predicate on the "refund_time" field.
func RefundTimeLT(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldRefundTime, v))
}

// RefundTimeLTE applies the LTE predicate on the "refund_time" field.
func RefundTimeLTE(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldRefundTime, v))
}

// RefundTimeIsNil applies the IsNil predicate on the "refund_time" field.
func RefundTimeIsNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIsNull(FieldRefundTime))
}

// RefundTimeNotNil applies the NotNil predicate on the "refund_time" field.
func RefundTimeNotNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotNull(FieldRefundTime))
}

// RefundReasonEQ applies the EQ predicate on the "refund_reason" field.
func RefundReasonEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldRefundReason, v))
}

// RefundReasonNEQ applies the NEQ predicate on the "refund_reason" field.
func RefundReasonNEQ(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldRefundReason, v))
}

// RefundReasonIn applies the In predicate on the "refund_reason" field.
func RefundReasonIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldRefundReason, vs...))
}

// RefundReasonNotIn applies the NotIn predicate on the "refund_reason" field.
func RefundReasonNotIn(vs ...string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldRefundReason, vs...))
}

// RefundReasonGT applies the GT predicate on the "refund_reason" field.
func RefundReasonGT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldRefundReason, v))
}

// RefundReasonGTE applies the GTE predicate on the "refund_reason" field.
func RefundReasonGTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldRefundReason, v))
}

// RefundReasonLT applies the LT predicate on the "refund_reason" field.
func RefundReasonLT(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldRefundReason, v))
}

// RefundReasonLTE applies the LTE predicate on the "refund_reason" field.
func RefundReasonLTE(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldRefundReason, v))
}

// RefundReasonContains applies the Contains predicate on the "refund_reason" field.
func RefundReasonContains(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContains(FieldRefundReason, v))
}

// RefundReasonHasPrefix applies the HasPrefix predicate on the "refund_reason" field.
func RefundReasonHasPrefix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasPrefix(FieldRefundReason, v))
}

// RefundReasonHasSuffix applies the HasSuffix predicate on the "refund_reason" field.
func RefundReasonHasSuffix(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldHasSuffix(FieldRefundReason, v))
}

// RefundReasonIsNil applies the IsNil predicate on the "refund_reason" field.
func RefundReasonIsNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIsNull(FieldRefundReason))
}

// RefundReasonNotNil applies the NotNil predicate on the "refund_reason" field.
func RefundReasonNotNil() predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotNull(FieldRefundReason))
}

// RefundReasonEqualFold applies the EqualFold predicate on the "refund_reason" field.
func RefundReasonEqualFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEqualFold(FieldRefundReason, v))
}

// RefundReasonContainsFold applies the ContainsFold predicate on the "refund_reason" field.
func RefundReasonContainsFold(v string) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldContainsFold(FieldRefundReason, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.FieldLTE(FieldUpdateTime, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PaymentRecord {
	return predicate.PaymentRecord(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PaymentRecord {
	return predicate.PaymentRecord(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PaymentRecord) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PaymentRecord) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PaymentRecord) predicate.PaymentRecord {
	return predicate.PaymentRecord(sql.NotPredicates(p))
}
