// Code generated by ent, DO NOT EDIT.

package agentlog

import (
	"time"
	"wood-passage-creator/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldID, id))
}

// ArticleID applies equality check predicate on the "article_id" field. It's identical to ArticleIDEQ.
func ArticleID(v int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldArticleID, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldTaskID, v))
}

// AgentName applies equality check predicate on the "agent_name" field. It's identical to AgentNameEQ.
func AgentName(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldAgentName, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldEndTime, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldDurationMs, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldErrorMessage, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldPrompt, v))
}

// InputData applies equality check predicate on the "input_data" field. It's identical to InputDataEQ.
func InputData(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldInputData, v))
}

// OutputData applies equality check predicate on the "output_data" field. It's identical to OutputDataEQ.
func OutputData(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldOutputData, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldUpdateTime, v))
}

// IsDelete applies equality check predicate on the "is_delete" field. It's identical to IsDeleteEQ.
func IsDelete(v bool) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldIsDelete, v))
}

// ArticleIDEQ applies the EQ predicate on the "article_id" field.
func ArticleIDEQ(v int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldArticleID, v))
}

// ArticleIDNEQ applies the NEQ predicate on the "article_id" field.
func ArticleIDNEQ(v int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldArticleID, v))
}

// ArticleIDIn applies the In predicate on the "article_id" field.
func ArticleIDIn(vs ...int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldArticleID, vs...))
}

// ArticleIDNotIn applies the NotIn predicate on the "article_id" field.
func ArticleIDNotIn(vs ...int64) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldArticleID, vs...))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContainsFold(FieldTaskID, v))
}

// AgentNameEQ applies the EQ predicate on the "agent_name" field.
func AgentNameEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldAgentName, v))
}

// AgentNameNEQ applies the NEQ predicate on the "agent_name" field.
func AgentNameNEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldAgentName, v))
}

// AgentNameIn applies the In predicate on the "agent_name" field.
func AgentNameIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldAgentName, vs...))
}

// AgentNameNotIn applies the NotIn predicate on the "agent_name" field.
func AgentNameNotIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldAgentName, vs...))
}

// AgentNameGT applies the GT predicate on the "agent_name" field.
func AgentNameGT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldAgentName, v))
}

// AgentNameGTE applies the GTE predicate on the "agent_name" field.
func AgentNameGTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldAgentName, v))
}

// AgentNameLT applies the LT predicate on the "agent_name" field.
func AgentNameLT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldAgentName, v))
}

// AgentNameLTE applies the LTE predicate on the "agent_name" field.
func AgentNameLTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldAgentName, v))
}

// AgentNameContains applies the Contains predicate on the "agent_name" field.
func AgentNameContains(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContains(FieldAgentName, v))
}

// AgentNameHasPrefix applies the HasPrefix predicate on the "agent_name" field.
func AgentNameHasPrefix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasPrefix(FieldAgentName, v))
}

// AgentNameHasSuffix applies the HasSuffix predicate on the "agent_name" field.
func AgentNameHasSuffix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasSuffix(FieldAgentName, v))
}

// AgentNameEqualFold applies the EqualFold predicate on the "agent_name" field.
func AgentNameEqualFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEqualFold(FieldAgentName, v))
}

// AgentNameContainsFold applies the ContainsFold predicate on the "agent_name" field.
func AgentNameContainsFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContainsFold(FieldAgentName, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeIsNil applies the IsNil predicate on the "end_time" field.
func EndTimeIsNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIsNull(FieldEndTime))
}

// EndTimeNotNil applies the NotNil predicate on the "end_time" field.
func EndTimeNotNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotNull(FieldEndTime))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotNull(FieldDurationMs))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContainsFold(FieldErrorMessage, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptIsNil applies the IsNil predicate on the "prompt" field.
func PromptIsNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIsNull(FieldPrompt))
}

// PromptNotNil applies the NotNil predicate on the "prompt" field.
func PromptNotNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotNull(FieldPrompt))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContainsFold(FieldPrompt, v))
}

// InputDataEQ applies the EQ predicate on the "input_data" field.
func InputDataEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldInputData, v))
}

// InputDataNEQ applies the NEQ predicate on the "input_data" field.
func InputDataNEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldInputData, v))
}

// InputDataIn applies the In predicate on the "input_data" field.
func InputDataIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldInputData, vs...))
}

// InputDataNotIn applies the NotIn predicate on the "input_data" field.
func InputDataNotIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldInputData, vs...))
}

// InputDataGT applies the GT predicate on the "input_data" field.
func InputDataGT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldInputData, v))
}

// InputDataGTE applies the GTE predicate on the "input_data" field.
func InputDataGTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldInputData, v))
}

// InputDataLT applies the LT predicate on the "input_data" field.
func InputDataLT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldInputData, v))
}

// InputDataLTE applies the LTE predicate on the "input_data" field.
func InputDataLTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldInputData, v))
}

// InputDataContains applies the Contains predicate on the "input_data" field.
func InputDataContains(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContains(FieldInputData, v))
}

// InputDataHasPrefix applies the HasPrefix predicate on the "input_data" field.
func InputDataHasPrefix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasPrefix(FieldInputData, v))
}

// InputDataHasSuffix applies the HasSuffix predicate on the "input_data" field.
func InputDataHasSuffix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasSuffix(FieldInputData, v))
}

// InputDataIsNil applies the IsNil predicate on the "input_data" field.
func InputDataIsNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIsNull(FieldInputData))
}

// InputDataNotNil applies the NotNil predicate on the "input_data" field.
func InputDataNotNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotNull(FieldInputData))
}

// InputDataEqualFold applies the EqualFold predicate on the "input_data" field.
func InputDataEqualFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEqualFold(FieldInputData, v))
}

// InputDataContainsFold applies the ContainsFold predicate on the "input_data" field.
func InputDataContainsFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContainsFold(FieldInputData, v))
}

// OutputDataEQ applies the EQ predicate on the "output_data" field.
func OutputDataEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldOutputData, v))
}

// OutputDataNEQ applies the NEQ predicate on the "output_data" field.
func OutputDataNEQ(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldOutputData, v))
}

// OutputDataIn applies the In predicate on the "output_data" field.
func OutputDataIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldOutputData, vs...))
}

// OutputDataNotIn applies the NotIn predicate on the "output_data" field.
func OutputDataNotIn(vs ...string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldOutputData, vs...))
}

// OutputDataGT applies the GT predicate on the "output_data" field.
func OutputDataGT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldOutputData, v))
}

// OutputDataGTE applies the GTE predicate on the "output_data" field.
func OutputDataGTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldOutputData, v))
}

// OutputDataLT applies the LT predicate on the "output_data" field.
func OutputDataLT(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldOutputData, v))
}

// OutputDataLTE applies the LTE predicate on the "output_data" field.
func OutputDataLTE(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldOutputData, v))
}

// OutputDataContains applies the Contains predicate on the "output_data" field.
func OutputDataContains(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContains(FieldOutputData, v))
}

// OutputDataHasPrefix applies the HasPrefix predicate on the "output_data" field.
func OutputDataHasPrefix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasPrefix(FieldOutputData, v))
}

// OutputDataHasSuffix applies the HasSuffix predicate on the "output_data" field.
func OutputDataHasSuffix(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldHasSuffix(FieldOutputData, v))
}

// OutputDataIsNil applies the IsNil predicate on the "output_data" field.
func OutputDataIsNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIsNull(FieldOutputData))
}

// OutputDataNotNil applies the NotNil predicate on the "output_data" field.
func OutputDataNotNil() predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotNull(FieldOutputData))
}

// OutputDataEqualFold applies the EqualFold predicate on the "output_data" field.
func OutputDataEqualFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEqualFold(FieldOutputData, v))
}

// OutputDataContainsFold applies the ContainsFold predicate on the "output_data" field.
func OutputDataContainsFold(v string) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldContainsFold(FieldOutputData, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldLTE(FieldUpdateTime, v))
}

// IsDeleteEQ applies the EQ predicate on the "is_delete" field.
func IsDeleteEQ(v bool) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldEQ(FieldIsDelete, v))
}

// IsDeleteNEQ applies the NEQ predicate on the "is_delete" field.
func IsDeleteNEQ(v bool) predicate.AgentLog {
	return predicate.AgentLog(sql.FieldNEQ(FieldIsDelete, v))
}

// HasArticle applies the HasEdge predicate on the "article" edge.
func HasArticle() predicate.AgentLog {
	return predicate.AgentLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ArticleTable, ArticleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArticleWith applies the HasEdge predicate on the "article" edge with a given conditions (other predicates).
func HasArticleWith(preds ...predicate.Article) predicate.AgentLog {
	return predicate.AgentLog(func(s *sql.Selector) {
		step := newArticleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AgentLog) predicate.AgentLog {
	return predicate.AgentLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AgentLog) predicate.AgentLog {
	return predicate.AgentLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AgentLog) predicate.AgentLog {
	return predicate.AgentLog(sql.NotPredicates(p))
}
