// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_account", Type: field.TypeString, Unique: true, Size: 256},
		{Name: "user_password", Type: field.TypeString, Size: 512},
		{Name: "user_name", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "user_avatar", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "user_profile", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "user_role", Type: field.TypeEnum, Enums: []string{"user", "admin", "vip"}, Default: "user"},
		{Name: "quota", Type: field.TypeInt, Default: 5},
		{Name: "vip_time", Type: field.TypeTime, Nullable: true},
		{Name: "edit_time", Type: field.TypeTime},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "is_delete", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_user_name",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[3]},
			},
			{
				Name:    "user_is_delete",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[12]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
