// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"projecttemp/ent/agentlog"
	"projecttemp/ent/article"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentLogCreate is the builder for creating a AgentLog entity.
type AgentLogCreate struct {
	config
	mutation *AgentLogMutation
	hooks    []Hook
}

// SetArticleID sets the "article_id" field.
func (_c *AgentLogCreate) SetArticleID(v int64) *AgentLogCreate {
	_c.mutation.SetArticleID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *AgentLogCreate) SetTaskID(v string) *AgentLogCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetAgentName sets the "agent_name" field.
func (_c *AgentLogCreate) SetAgentName(v string) *AgentLogCreate {
	_c.mutation.SetAgentName(v)
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *AgentLogCreate) SetStartTime(v time.Time) *AgentLogCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *AgentLogCreate) SetEndTime(v time.Time) *AgentLogCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableEndTime(v *time.Time) *AgentLogCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *AgentLogCreate) SetDurationMs(v int) *AgentLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableDurationMs(v *int) *AgentLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentLogCreate) SetStatus(v agentlog.Status) *AgentLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *AgentLogCreate) SetErrorMessage(v string) *AgentLogCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableErrorMessage(v *string) *AgentLogCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *AgentLogCreate) SetPrompt(v string) *AgentLogCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillablePrompt(v *string) *AgentLogCreate {
	if v != nil {
		_c.SetPrompt(*v)
	}
	return _c
}

// SetInputData sets the "input_data" field.
func (_c *AgentLogCreate) SetInputData(v string) *AgentLogCreate {
	_c.mutation.SetInputData(v)
	return _c
}

// SetNillableInputData sets the "input_data" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableInputData(v *string) *AgentLogCreate {
	if v != nil {
		_c.SetInputData(*v)
	}
	return _c
}

// SetOutputData sets the "output_data" field.
func (_c *AgentLogCreate) SetOutputData(v string) *AgentLogCreate {
	_c.mutation.SetOutputData(v)
	return _c
}

// SetNillableOutputData sets the "output_data" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableOutputData(v *string) *AgentLogCreate {
	if v != nil {
		_c.SetOutputData(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *AgentLogCreate) SetCreateTime(v time.Time) *AgentLogCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableCreateTime(v *time.Time) *AgentLogCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *AgentLogCreate) SetUpdateTime(v time.Time) *AgentLogCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableUpdateTime(v *time.Time) *AgentLogCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "is_delete" field.
func (_c *AgentLogCreate) SetIsDelete(v bool) *AgentLogCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_c *AgentLogCreate) SetNillableIsDelete(v *bool) *AgentLogCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentLogCreate) SetID(v int64) *AgentLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetArticle sets the "article" edge to the Article entity.
func (_c *AgentLogCreate) SetArticle(v *Article) *AgentLogCreate {
	return _c.SetArticleID(v.ID)
}

// Mutation returns the AgentLogMutation object of the builder.
func (_c *AgentLogCreate) Mutation() *AgentLogMutation {
	return _c.mutation
}

// Save creates the AgentLog in the database.
func (_c *AgentLogCreate) Save(ctx context.Context) (*AgentLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentLogCreate) SaveX(ctx context.Context) *AgentLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentLogCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := agentlog.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := agentlog.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := agentlog.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentLogCreate) check() error {
	if _, ok := _c.mutation.ArticleID(); !ok {
		return &ValidationError{Name: "article_id", err: errors.New(`ent: missing required field "AgentLog.article_id"`)}
	}
	if v, ok := _c.mutation.ArticleID(); ok {
		if err := agentlog.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "AgentLog.article_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "AgentLog.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := agentlog.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "AgentLog.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AgentName(); !ok {
		return &ValidationError{Name: "agent_name", err: errors.New(`ent: missing required field "AgentLog.agent_name"`)}
	}
	if v, ok := _c.mutation.AgentName(); ok {
		if err := agentlog.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "AgentLog.agent_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "AgentLog.start_time"`)}
	}
	if v, ok := _c.mutation.DurationMs(); ok {
		if err := agentlog.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "AgentLog.duration_ms": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := agentlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentLog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "AgentLog.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "AgentLog.update_time"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "is_delete", err: errors.New(`ent: missing required field "AgentLog.is_delete"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := agentlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "AgentLog.id": %w`, err)}
		}
	}
	if len(_c.mutation.ArticleIDs()) == 0 {
		return &ValidationError{Name: "article", err: errors.New(`ent: missing required edge "AgentLog.article"`)}
	}
	return nil
}

func (_c *AgentLogCreate) sqlSave(ctx context.Context) (*AgentLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentLogCreate) createSpec() (*AgentLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agentlog.Table, sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(agentlog.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.AgentName(); ok {
		_spec.SetField(agentlog.FieldAgentName, field.TypeString, value)
		_node.AgentName = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(agentlog.FieldStartTime, field.TypeTime, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(agentlog.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(agentlog.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agentlog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(agentlog.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(agentlog.FieldPrompt, field.TypeString, value)
		_node.Prompt = &value
	}
	if value, ok := _c.mutation.InputData(); ok {
		_spec.SetField(agentlog.FieldInputData, field.TypeString, value)
		_node.InputData = &value
	}
	if value, ok := _c.mutation.OutputData(); ok {
		_spec.SetField(agentlog.FieldOutputData, field.TypeString, value)
		_node.OutputData = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(agentlog.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(agentlog.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(agentlog.FieldIsDelete, field.TypeBool, value)
		_node.IsDelete = value
	}
	if nodes := _c.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentlog.ArticleTable,
			Columns: []string{agentlog.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ArticleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentLogCreateBulk is the builder for creating many AgentLog entities in bulk.
type AgentLogCreateBulk struct {
	config
	err      error
	builders []*AgentLogCreate
}

// Save creates the AgentLog entities in the database.
func (_c *AgentLogCreateBulk) Save(ctx context.Context) ([]*AgentLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentLogCreateBulk) SaveX(ctx context.Context) []*AgentLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
