// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"projecttemp/ent/agentlog"
	"projecttemp/ent/article"
	"projecttemp/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentLogUpdate is the builder for updating AgentLog entities.
type AgentLogUpdate struct {
	config
	hooks    []Hook
	mutation *AgentLogMutation
}

// Where appends a list predicates to the AgentLogUpdate builder.
func (_u *AgentLogUpdate) Where(ps ...predicate.AgentLog) *AgentLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetArticleID sets the "article_id" field.
func (_u *AgentLogUpdate) SetArticleID(v int64) *AgentLogUpdate {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableArticleID(v *int64) *AgentLogUpdate {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *AgentLogUpdate) SetTaskID(v string) *AgentLogUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableTaskID(v *string) *AgentLogUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetAgentName sets the "agent_name" field.
func (_u *AgentLogUpdate) SetAgentName(v string) *AgentLogUpdate {
	_u.mutation.SetAgentName(v)
	return _u
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableAgentName(v *string) *AgentLogUpdate {
	if v != nil {
		_u.SetAgentName(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *AgentLogUpdate) SetStartTime(v time.Time) *AgentLogUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableStartTime(v *time.Time) *AgentLogUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *AgentLogUpdate) SetEndTime(v time.Time) *AgentLogUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableEndTime(v *time.Time) *AgentLogUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *AgentLogUpdate) ClearEndTime() *AgentLogUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AgentLogUpdate) SetDurationMs(v int) *AgentLogUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableDurationMs(v *int) *AgentLogUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AgentLogUpdate) AddDurationMs(v int) *AgentLogUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AgentLogUpdate) ClearDurationMs() *AgentLogUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentLogUpdate) SetStatus(v agentlog.Status) *AgentLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableStatus(v *agentlog.Status) *AgentLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AgentLogUpdate) SetErrorMessage(v string) *AgentLogUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableErrorMessage(v *string) *AgentLogUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AgentLogUpdate) ClearErrorMessage() *AgentLogUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *AgentLogUpdate) SetPrompt(v string) *AgentLogUpdate {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillablePrompt(v *string) *AgentLogUpdate {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// ClearPrompt clears the value of the "prompt" field.
func (_u *AgentLogUpdate) ClearPrompt() *AgentLogUpdate {
	_u.mutation.ClearPrompt()
	return _u
}

// SetInputData sets the "input_data" field.
func (_u *AgentLogUpdate) SetInputData(v string) *AgentLogUpdate {
	_u.mutation.SetInputData(v)
	return _u
}

// SetNillableInputData sets the "input_data" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableInputData(v *string) *AgentLogUpdate {
	if v != nil {
		_u.SetInputData(*v)
	}
	return _u
}

// ClearInputData clears the value of the "input_data" field.
func (_u *AgentLogUpdate) ClearInputData() *AgentLogUpdate {
	_u.mutation.ClearInputData()
	return _u
}

// SetOutputData sets the "output_data" field.
func (_u *AgentLogUpdate) SetOutputData(v string) *AgentLogUpdate {
	_u.mutation.SetOutputData(v)
	return _u
}

// SetNillableOutputData sets the "output_data" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableOutputData(v *string) *AgentLogUpdate {
	if v != nil {
		_u.SetOutputData(*v)
	}
	return _u
}

// ClearOutputData clears the value of the "output_data" field.
func (_u *AgentLogUpdate) ClearOutputData() *AgentLogUpdate {
	_u.mutation.ClearOutputData()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AgentLogUpdate) SetUpdateTime(v time.Time) *AgentLogUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *AgentLogUpdate) SetIsDelete(v bool) *AgentLogUpdate {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *AgentLogUpdate) SetNillableIsDelete(v *bool) *AgentLogUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *AgentLogUpdate) SetArticle(v *Article) *AgentLogUpdate {
	return _u.SetArticleID(v.ID)
}

// Mutation returns the AgentLogMutation object of the builder.
func (_u *AgentLogUpdate) Mutation() *AgentLogMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *AgentLogUpdate) ClearArticle() *AgentLogUpdate {
	_u.mutation.ClearArticle()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := agentlog.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentLogUpdate) check() error {
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := agentlog.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "AgentLog.article_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskID(); ok {
		if err := agentlog.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "AgentLog.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AgentName(); ok {
		if err := agentlog.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "AgentLog.agent_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := agentlog.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "AgentLog.duration_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentLog.status": %w`, err)}
		}
	}
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentLog.article"`)
	}
	return nil
}

func (_u *AgentLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentlog.Table, agentlog.Columns, sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(agentlog.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentName(); ok {
		_spec.SetField(agentlog.FieldAgentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(agentlog.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(agentlog.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(agentlog.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(agentlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(agentlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(agentlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(agentlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(agentlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(agentlog.FieldPrompt, field.TypeString, value)
	}
	if _u.mutation.PromptCleared() {
		_spec.ClearField(agentlog.FieldPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.InputData(); ok {
		_spec.SetField(agentlog.FieldInputData, field.TypeString, value)
	}
	if _u.mutation.InputDataCleared() {
		_spec.ClearField(agentlog.FieldInputData, field.TypeString)
	}
	if value, ok := _u.mutation.OutputData(); ok {
		_spec.SetField(agentlog.FieldOutputData, field.TypeString, value)
	}
	if _u.mutation.OutputDataCleared() {
		_spec.ClearField(agentlog.FieldOutputData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(agentlog.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(agentlog.FieldIsDelete, field.TypeBool, value)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentlog.ArticleTable,
			Columns: []string{agentlog.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentlog.ArticleTable,
			Columns: []string{agentlog.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentLogUpdateOne is the builder for updating a single AgentLog entity.
type AgentLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentLogMutation
}

// SetArticleID sets the "article_id" field.
func (_u *AgentLogUpdateOne) SetArticleID(v int64) *AgentLogUpdateOne {
	_u.mutation.SetArticleID(v)
	return _u
}

// SetNillableArticleID sets the "article_id" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableArticleID(v *int64) *AgentLogUpdateOne {
	if v != nil {
		_u.SetArticleID(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *AgentLogUpdateOne) SetTaskID(v string) *AgentLogUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableTaskID(v *string) *AgentLogUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetAgentName sets the "agent_name" field.
func (_u *AgentLogUpdateOne) SetAgentName(v string) *AgentLogUpdateOne {
	_u.mutation.SetAgentName(v)
	return _u
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableAgentName(v *string) *AgentLogUpdateOne {
	if v != nil {
		_u.SetAgentName(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *AgentLogUpdateOne) SetStartTime(v time.Time) *AgentLogUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableStartTime(v *time.Time) *AgentLogUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *AgentLogUpdateOne) SetEndTime(v time.Time) *AgentLogUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableEndTime(v *time.Time) *AgentLogUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *AgentLogUpdateOne) ClearEndTime() *AgentLogUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *AgentLogUpdateOne) SetDurationMs(v int) *AgentLogUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableDurationMs(v *int) *AgentLogUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *AgentLogUpdateOne) AddDurationMs(v int) *AgentLogUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *AgentLogUpdateOne) ClearDurationMs() *AgentLogUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentLogUpdateOne) SetStatus(v agentlog.Status) *AgentLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableStatus(v *agentlog.Status) *AgentLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *AgentLogUpdateOne) SetErrorMessage(v string) *AgentLogUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableErrorMessage(v *string) *AgentLogUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *AgentLogUpdateOne) ClearErrorMessage() *AgentLogUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetPrompt sets the "prompt" field.
func (_u *AgentLogUpdateOne) SetPrompt(v string) *AgentLogUpdateOne {
	_u.mutation.SetPrompt(v)
	return _u
}

// SetNillablePrompt sets the "prompt" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillablePrompt(v *string) *AgentLogUpdateOne {
	if v != nil {
		_u.SetPrompt(*v)
	}
	return _u
}

// ClearPrompt clears the value of the "prompt" field.
func (_u *AgentLogUpdateOne) ClearPrompt() *AgentLogUpdateOne {
	_u.mutation.ClearPrompt()
	return _u
}

// SetInputData sets the "input_data" field.
func (_u *AgentLogUpdateOne) SetInputData(v string) *AgentLogUpdateOne {
	_u.mutation.SetInputData(v)
	return _u
}

// SetNillableInputData sets the "input_data" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableInputData(v *string) *AgentLogUpdateOne {
	if v != nil {
		_u.SetInputData(*v)
	}
	return _u
}

// ClearInputData clears the value of the "input_data" field.
func (_u *AgentLogUpdateOne) ClearInputData() *AgentLogUpdateOne {
	_u.mutation.ClearInputData()
	return _u
}

// SetOutputData sets the "output_data" field.
func (_u *AgentLogUpdateOne) SetOutputData(v string) *AgentLogUpdateOne {
	_u.mutation.SetOutputData(v)
	return _u
}

// SetNillableOutputData sets the "output_data" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableOutputData(v *string) *AgentLogUpdateOne {
	if v != nil {
		_u.SetOutputData(*v)
	}
	return _u
}

// ClearOutputData clears the value of the "output_data" field.
func (_u *AgentLogUpdateOne) ClearOutputData() *AgentLogUpdateOne {
	_u.mutation.ClearOutputData()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *AgentLogUpdateOne) SetUpdateTime(v time.Time) *AgentLogUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *AgentLogUpdateOne) SetIsDelete(v bool) *AgentLogUpdateOne {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *AgentLogUpdateOne) SetNillableIsDelete(v *bool) *AgentLogUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetArticle sets the "article" edge to the Article entity.
func (_u *AgentLogUpdateOne) SetArticle(v *Article) *AgentLogUpdateOne {
	return _u.SetArticleID(v.ID)
}

// Mutation returns the AgentLogMutation object of the builder.
func (_u *AgentLogUpdateOne) Mutation() *AgentLogMutation {
	return _u.mutation
}

// ClearArticle clears the "article" edge to the Article entity.
func (_u *AgentLogUpdateOne) ClearArticle() *AgentLogUpdateOne {
	_u.mutation.ClearArticle()
	return _u
}

// Where appends a list predicates to the AgentLogUpdate builder.
func (_u *AgentLogUpdateOne) Where(ps ...predicate.AgentLog) *AgentLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentLogUpdateOne) Select(field string, fields ...string) *AgentLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentLog entity.
func (_u *AgentLogUpdateOne) Save(ctx context.Context) (*AgentLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentLogUpdateOne) SaveX(ctx context.Context) *AgentLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := agentlog.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentLogUpdateOne) check() error {
	if v, ok := _u.mutation.ArticleID(); ok {
		if err := agentlog.ArticleIDValidator(v); err != nil {
			return &ValidationError{Name: "article_id", err: fmt.Errorf(`ent: validator failed for field "AgentLog.article_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskID(); ok {
		if err := agentlog.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "AgentLog.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AgentName(); ok {
		if err := agentlog.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "AgentLog.agent_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationMs(); ok {
		if err := agentlog.DurationMsValidator(v); err != nil {
			return &ValidationError{Name: "duration_ms", err: fmt.Errorf(`ent: validator failed for field "AgentLog.duration_ms": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agentlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AgentLog.status": %w`, err)}
		}
	}
	if _u.mutation.ArticleCleared() && len(_u.mutation.ArticleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentLog.article"`)
	}
	return nil
}

func (_u *AgentLogUpdateOne) sqlSave(ctx context.Context) (_node *AgentLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentlog.Table, agentlog.Columns, sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentlog.FieldID)
		for _, f := range fields {
			if !agentlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(agentlog.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentName(); ok {
		_spec.SetField(agentlog.FieldAgentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(agentlog.FieldStartTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(agentlog.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(agentlog.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(agentlog.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(agentlog.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(agentlog.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentlog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(agentlog.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(agentlog.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Prompt(); ok {
		_spec.SetField(agentlog.FieldPrompt, field.TypeString, value)
	}
	if _u.mutation.PromptCleared() {
		_spec.ClearField(agentlog.FieldPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.InputData(); ok {
		_spec.SetField(agentlog.FieldInputData, field.TypeString, value)
	}
	if _u.mutation.InputDataCleared() {
		_spec.ClearField(agentlog.FieldInputData, field.TypeString)
	}
	if value, ok := _u.mutation.OutputData(); ok {
		_spec.SetField(agentlog.FieldOutputData, field.TypeString, value)
	}
	if _u.mutation.OutputDataCleared() {
		_spec.ClearField(agentlog.FieldOutputData, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(agentlog.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(agentlog.FieldIsDelete, field.TypeBool, value)
	}
	if _u.mutation.ArticleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentlog.ArticleTable,
			Columns: []string{agentlog.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentlog.ArticleTable,
			Columns: []string{agentlog.ArticleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
