// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"
	"wood-passage-creator/ent/agentlog"
	"wood-passage-creator/ent/article"
	"wood-passage-creator/ent/user"
	"wood-passage-creator/internal/port"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticleCreate is the builder for creating a Article entity.
type ArticleCreate struct {
	config
	mutation *ArticleMutation
	hooks    []Hook
}

// SetTaskID sets the "task_id" field.
func (_c *ArticleCreate) SetTaskID(v string) *ArticleCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ArticleCreate) SetUserID(v int64) *ArticleCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTopic sets the "topic" field.
func (_c *ArticleCreate) SetTopic(v string) *ArticleCreate {
	_c.mutation.SetTopic(v)
	return _c
}

// SetUserDescription sets the "user_description" field.
func (_c *ArticleCreate) SetUserDescription(v string) *ArticleCreate {
	_c.mutation.SetUserDescription(v)
	return _c
}

// SetNillableUserDescription sets the "user_description" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableUserDescription(v *string) *ArticleCreate {
	if v != nil {
		_c.SetUserDescription(*v)
	}
	return _c
}

// SetMainTitle sets the "main_title" field.
func (_c *ArticleCreate) SetMainTitle(v string) *ArticleCreate {
	_c.mutation.SetMainTitle(v)
	return _c
}

// SetNillableMainTitle sets the "main_title" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableMainTitle(v *string) *ArticleCreate {
	if v != nil {
		_c.SetMainTitle(*v)
	}
	return _c
}

// SetSubTitle sets the "sub_title" field.
func (_c *ArticleCreate) SetSubTitle(v string) *ArticleCreate {
	_c.mutation.SetSubTitle(v)
	return _c
}

// SetNillableSubTitle sets the "sub_title" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableSubTitle(v *string) *ArticleCreate {
	if v != nil {
		_c.SetSubTitle(*v)
	}
	return _c
}

// SetTitleOptions sets the "title_options" field.
func (_c *ArticleCreate) SetTitleOptions(v json.RawMessage) *ArticleCreate {
	_c.mutation.SetTitleOptions(v)
	return _c
}

// SetOutline sets the "outline" field.
func (_c *ArticleCreate) SetOutline(v json.RawMessage) *ArticleCreate {
	_c.mutation.SetOutline(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ArticleCreate) SetContent(v string) *ArticleCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableContent(v *string) *ArticleCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetFullContent sets the "full_content" field.
func (_c *ArticleCreate) SetFullContent(v string) *ArticleCreate {
	_c.mutation.SetFullContent(v)
	return _c
}

// SetNillableFullContent sets the "full_content" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableFullContent(v *string) *ArticleCreate {
	if v != nil {
		_c.SetFullContent(*v)
	}
	return _c
}

// SetImages sets the "images" field.
func (_c *ArticleCreate) SetImages(v json.RawMessage) *ArticleCreate {
	_c.mutation.SetImages(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ArticleCreate) SetStatus(v article.Status) *ArticleCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableStatus(v *article.Status) *ArticleCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPhase sets the "phase" field.
func (_c *ArticleCreate) SetPhase(v article.Phase) *ArticleCreate {
	_c.mutation.SetPhase(v)
	return _c
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_c *ArticleCreate) SetNillablePhase(v *article.Phase) *ArticleCreate {
	if v != nil {
		_c.SetPhase(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ArticleCreate) SetErrorMessage(v string) *ArticleCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableErrorMessage(v *string) *ArticleCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetStyle sets the "style" field.
func (_c *ArticleCreate) SetStyle(v article.Style) *ArticleCreate {
	_c.mutation.SetStyle(v)
	return _c
}

// SetNillableStyle sets the "style" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableStyle(v *article.Style) *ArticleCreate {
	if v != nil {
		_c.SetStyle(*v)
	}
	return _c
}

// SetEnabledImageMethods sets the "enabled_image_methods" field.
func (_c *ArticleCreate) SetEnabledImageMethods(v []port.ImageMethod) *ArticleCreate {
	_c.mutation.SetEnabledImageMethods(v)
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ArticleCreate) SetCreateTime(v time.Time) *ArticleCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableCreateTime(v *time.Time) *ArticleCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetCompletedTime sets the "completed_time" field.
func (_c *ArticleCreate) SetCompletedTime(v time.Time) *ArticleCreate {
	_c.mutation.SetCompletedTime(v)
	return _c
}

// SetNillableCompletedTime sets the "completed_time" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableCompletedTime(v *time.Time) *ArticleCreate {
	if v != nil {
		_c.SetCompletedTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ArticleCreate) SetUpdateTime(v time.Time) *ArticleCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableUpdateTime(v *time.Time) *ArticleCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "is_delete" field.
func (_c *ArticleCreate) SetIsDelete(v bool) *ArticleCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_c *ArticleCreate) SetNillableIsDelete(v *bool) *ArticleCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ArticleCreate) SetID(v int64) *ArticleCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ArticleCreate) SetUser(v *User) *ArticleCreate {
	return _c.SetUserID(v.ID)
}

// AddAgentLogIDs adds the "agent_logs" edge to the AgentLog entity by IDs.
func (_c *ArticleCreate) AddAgentLogIDs(ids ...int64) *ArticleCreate {
	_c.mutation.AddAgentLogIDs(ids...)
	return _c
}

// AddAgentLogs adds the "agent_logs" edges to the AgentLog entity.
func (_c *ArticleCreate) AddAgentLogs(v ...*AgentLog) *ArticleCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAgentLogIDs(ids...)
}

// Mutation returns the ArticleMutation object of the builder.
func (_c *ArticleCreate) Mutation() *ArticleMutation {
	return _c.mutation
}

// Save creates the Article in the database.
func (_c *ArticleCreate) Save(ctx context.Context) (*Article, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArticleCreate) SaveX(ctx context.Context) *Article {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArticleCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := article.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Phase(); !ok {
		v := article.DefaultPhase
		_c.mutation.SetPhase(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := article.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := article.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := article.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArticleCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "Article.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := article.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "Article.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Article.user_id"`)}
	}
	if _, ok := _c.mutation.Topic(); !ok {
		return &ValidationError{Name: "topic", err: errors.New(`ent: missing required field "Article.topic"`)}
	}
	if v, ok := _c.mutation.Topic(); ok {
		if err := article.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "Article.topic": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Article.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := article.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Article.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phase(); !ok {
		return &ValidationError{Name: "phase", err: errors.New(`ent: missing required field "Article.phase"`)}
	}
	if v, ok := _c.mutation.Phase(); ok {
		if err := article.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Article.phase": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Style(); ok {
		if err := article.StyleValidator(v); err != nil {
			return &ValidationError{Name: "style", err: fmt.Errorf(`ent: validator failed for field "Article.style": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Article.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Article.update_time"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "is_delete", err: errors.New(`ent: missing required field "Article.is_delete"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := article.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Article.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Article.user"`)}
	}
	return nil
}

func (_c *ArticleCreate) sqlSave(ctx context.Context) (*Article, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArticleCreate) createSpec() (*Article, *sqlgraph.CreateSpec) {
	var (
		_node = &Article{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(article.Table, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(article.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.Topic(); ok {
		_spec.SetField(article.FieldTopic, field.TypeString, value)
		_node.Topic = value
	}
	if value, ok := _c.mutation.UserDescription(); ok {
		_spec.SetField(article.FieldUserDescription, field.TypeString, value)
		_node.UserDescription = &value
	}
	if value, ok := _c.mutation.MainTitle(); ok {
		_spec.SetField(article.FieldMainTitle, field.TypeString, value)
		_node.MainTitle = &value
	}
	if value, ok := _c.mutation.SubTitle(); ok {
		_spec.SetField(article.FieldSubTitle, field.TypeString, value)
		_node.SubTitle = &value
	}
	if value, ok := _c.mutation.TitleOptions(); ok {
		_spec.SetField(article.FieldTitleOptions, field.TypeJSON, value)
		_node.TitleOptions = value
	}
	if value, ok := _c.mutation.Outline(); ok {
		_spec.SetField(article.FieldOutline, field.TypeJSON, value)
		_node.Outline = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
		_node.Content = &value
	}
	if value, ok := _c.mutation.FullContent(); ok {
		_spec.SetField(article.FieldFullContent, field.TypeString, value)
		_node.FullContent = &value
	}
	if value, ok := _c.mutation.Images(); ok {
		_spec.SetField(article.FieldImages, field.TypeJSON, value)
		_node.Images = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(article.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Phase(); ok {
		_spec.SetField(article.FieldPhase, field.TypeEnum, value)
		_node.Phase = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(article.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.Style(); ok {
		_spec.SetField(article.FieldStyle, field.TypeEnum, value)
		_node.Style = value
	}
	if value, ok := _c.mutation.EnabledImageMethods(); ok {
		_spec.SetField(article.FieldEnabledImageMethods, field.TypeJSON, value)
		_node.EnabledImageMethods = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(article.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.CompletedTime(); ok {
		_spec.SetField(article.FieldCompletedTime, field.TypeTime, value)
		_node.CompletedTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(article.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(article.FieldIsDelete, field.TypeBool, value)
		_node.IsDelete = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.UserTable,
			Columns: []string{article.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AgentLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   article.AgentLogsTable,
			Columns: []string{article.AgentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ArticleCreateBulk is the builder for creating many Article entities in bulk.
type ArticleCreateBulk struct {
	config
	err      error
	builders []*ArticleCreate
}

// Save creates the Article entities in the database.
func (_c *ArticleCreateBulk) Save(ctx context.Context) ([]*Article, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Article, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArticleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArticleCreateBulk) SaveX(ctx context.Context) []*Article {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
