// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"projecttemp/ent/article"
	"projecttemp/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Article is the model entity for the Article schema.
type Article struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID int64 `json:"id,omitempty"`
	// 任务 ID，唯一
	TaskID string `json:"task_id,omitempty"`
	// 所属用户 ID
	UserID int64 `json:"user_id,omitempty"`
	// 文章主题
	Topic string `json:"topic,omitempty"`
	// 用户补充描述
	UserDescription *string `json:"user_description,omitempty"`
	// 主标题
	MainTitle *string `json:"main_title,omitempty"`
	// 副标题
	SubTitle *string `json:"sub_title,omitempty"`
	// 标题方案列表（JSON）
	TitleOptions json.RawMessage `json:"title_options,omitempty"`
	// 大纲（JSON）
	Outline json.RawMessage `json:"outline,omitempty"`
	// 正文内容
	Content *string `json:"content,omitempty"`
	// 完整内容（含配图等）
	FullContent *string `json:"full_content,omitempty"`
	// 配图结果列表（JSON）
	Images json.RawMessage `json:"images,omitempty"`
	// 文章状态：PENDING/PROCESSING/COMPLETED/FAILED
	Status article.Status `json:"status,omitempty"`
	// 当前阶段：PENDING/TITLE_GENERATING/TITLE_SELECTING/OUTLINE_GENERATING/OUTLINE_EDITING/CONTENT_GENERATING
	Phase article.Phase `json:"phase,omitempty"`
	// 失败错误信息
	ErrorMessage *string `json:"error_message,omitempty"`
	// 文章风格：tech/emotional/educational/humorous
	Style string `json:"style,omitempty"`
	// 允许的配图方式列表（JSON）
	EnabledImageMethods []string `json:"enabled_image_methods,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"create_time,omitempty"`
	// 完成时间
	CompletedTime *time.Time `json:"completed_time,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"update_time,omitempty"`
	// 是否删除（软删除）
	IsDelete bool `json:"is_delete,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArticleQuery when eager-loading is set.
	Edges        ArticleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ArticleEdges holds the relations/edges for other nodes in the graph.
type ArticleEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// AgentLogs holds the value of the agent_logs edge.
	AgentLogs []*AgentLog `json:"agent_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArticleEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AgentLogsOrErr returns the AgentLogs value or an error if the edge
// was not loaded in eager-loading.
func (e ArticleEdges) AgentLogsOrErr() ([]*AgentLog, error) {
	if e.loadedTypes[1] {
		return e.AgentLogs, nil
	}
	return nil, &NotLoadedError{edge: "agent_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Article) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case article.FieldTitleOptions, article.FieldOutline, article.FieldImages, article.FieldEnabledImageMethods:
			values[i] = new([]byte)
		case article.FieldIsDelete:
			values[i] = new(sql.NullBool)
		case article.FieldID, article.FieldUserID:
			values[i] = new(sql.NullInt64)
		case article.FieldTaskID, article.FieldTopic, article.FieldUserDescription, article.FieldMainTitle, article.FieldSubTitle, article.FieldContent, article.FieldFullContent, article.FieldStatus, article.FieldPhase, article.FieldErrorMessage, article.FieldStyle:
			values[i] = new(sql.NullString)
		case article.FieldCreateTime, article.FieldCompletedTime, article.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Article fields.
func (_m *Article) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case article.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case article.FieldTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value.Valid {
				_m.TaskID = value.String
			}
		case article.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case article.FieldTopic:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field topic", values[i])
			} else if value.Valid {
				_m.Topic = value.String
			}
		case article.FieldUserDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_description", values[i])
			} else if value.Valid {
				_m.UserDescription = new(string)
				*_m.UserDescription = value.String
			}
		case article.FieldMainTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field main_title", values[i])
			} else if value.Valid {
				_m.MainTitle = new(string)
				*_m.MainTitle = value.String
			}
		case article.FieldSubTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sub_title", values[i])
			} else if value.Valid {
				_m.SubTitle = new(string)
				*_m.SubTitle = value.String
			}
		case article.FieldTitleOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field title_options", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TitleOptions); err != nil {
					return fmt.Errorf("unmarshal field title_options: %w", err)
				}
			}
		case article.FieldOutline:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field outline", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Outline); err != nil {
					return fmt.Errorf("unmarshal field outline: %w", err)
				}
			}
		case article.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = new(string)
				*_m.Content = value.String
			}
		case article.FieldFullContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_content", values[i])
			} else if value.Valid {
				_m.FullContent = new(string)
				*_m.FullContent = value.String
			}
		case article.FieldImages:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field images", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Images); err != nil {
					return fmt.Errorf("unmarshal field images: %w", err)
				}
			}
		case article.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = article.Status(value.String)
			}
		case article.FieldPhase:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phase", values[i])
			} else if value.Valid {
				_m.Phase = article.Phase(value.String)
			}
		case article.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case article.FieldStyle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field style", values[i])
			} else if value.Valid {
				_m.Style = value.String
			}
		case article.FieldEnabledImageMethods:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field enabled_image_methods", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.EnabledImageMethods); err != nil {
					return fmt.Errorf("unmarshal field enabled_image_methods: %w", err)
				}
			}
		case article.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case article.FieldCompletedTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_time", values[i])
			} else if value.Valid {
				_m.CompletedTime = new(time.Time)
				*_m.CompletedTime = value.Time
			}
		case article.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case article.FieldIsDelete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_delete", values[i])
			} else if value.Valid {
				_m.IsDelete = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Article.
// This includes values selected through modifiers, order, etc.
func (_m *Article) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Article entity.
func (_m *Article) QueryUser() *UserQuery {
	return NewArticleClient(_m.config).QueryUser(_m)
}

// QueryAgentLogs queries the "agent_logs" edge of the Article entity.
func (_m *Article) QueryAgentLogs() *AgentLogQuery {
	return NewArticleClient(_m.config).QueryAgentLogs(_m)
}

// Update returns a builder for updating this Article.
// Note that you need to call Article.Unwrap() before calling this method if this Article
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Article) Update() *ArticleUpdateOne {
	return NewArticleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Article entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Article) Unwrap() *Article {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Article is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Article) String() string {
	var builder strings.Builder
	builder.WriteString("Article(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_id=")
	builder.WriteString(_m.TaskID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("topic=")
	builder.WriteString(_m.Topic)
	builder.WriteString(", ")
	if v := _m.UserDescription; v != nil {
		builder.WriteString("user_description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MainTitle; v != nil {
		builder.WriteString("main_title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SubTitle; v != nil {
		builder.WriteString("sub_title=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("title_options=")
	builder.WriteString(fmt.Sprintf("%v", _m.TitleOptions))
	builder.WriteString(", ")
	builder.WriteString("outline=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outline))
	builder.WriteString(", ")
	if v := _m.Content; v != nil {
		builder.WriteString("content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.FullContent; v != nil {
		builder.WriteString("full_content=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("images=")
	builder.WriteString(fmt.Sprintf("%v", _m.Images))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("phase=")
	builder.WriteString(fmt.Sprintf("%v", _m.Phase))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("style=")
	builder.WriteString(_m.Style)
	builder.WriteString(", ")
	builder.WriteString("enabled_image_methods=")
	builder.WriteString(fmt.Sprintf("%v", _m.EnabledImageMethods))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.CompletedTime; v != nil {
		builder.WriteString("completed_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_delete=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDelete))
	builder.WriteByte(')')
	return builder.String()
}

// Articles is a parsable slice of Article.
type Articles []*Article
