// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"
	"wood-passage-creator/ent/agentlog"
	"wood-passage-creator/ent/article"
	"wood-passage-creator/ent/predicate"
	"wood-passage-creator/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *ArticleUpdate) SetTaskID(v string) *ArticleUpdate {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableTaskID(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ArticleUpdate) SetUserID(v int64) *ArticleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableUserID(v *int64) *ArticleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *ArticleUpdate) SetTopic(v string) *ArticleUpdate {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableTopic(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetUserDescription sets the "user_description" field.
func (_u *ArticleUpdate) SetUserDescription(v string) *ArticleUpdate {
	_u.mutation.SetUserDescription(v)
	return _u
}

// SetNillableUserDescription sets the "user_description" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableUserDescription(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetUserDescription(*v)
	}
	return _u
}

// ClearUserDescription clears the value of the "user_description" field.
func (_u *ArticleUpdate) ClearUserDescription() *ArticleUpdate {
	_u.mutation.ClearUserDescription()
	return _u
}

// SetMainTitle sets the "main_title" field.
func (_u *ArticleUpdate) SetMainTitle(v string) *ArticleUpdate {
	_u.mutation.SetMainTitle(v)
	return _u
}

// SetNillableMainTitle sets the "main_title" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableMainTitle(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetMainTitle(*v)
	}
	return _u
}

// ClearMainTitle clears the value of the "main_title" field.
func (_u *ArticleUpdate) ClearMainTitle() *ArticleUpdate {
	_u.mutation.ClearMainTitle()
	return _u
}

// SetSubTitle sets the "sub_title" field.
func (_u *ArticleUpdate) SetSubTitle(v string) *ArticleUpdate {
	_u.mutation.SetSubTitle(v)
	return _u
}

// SetNillableSubTitle sets the "sub_title" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableSubTitle(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetSubTitle(*v)
	}
	return _u
}

// ClearSubTitle clears the value of the "sub_title" field.
func (_u *ArticleUpdate) ClearSubTitle() *ArticleUpdate {
	_u.mutation.ClearSubTitle()
	return _u
}

// SetTitleOptions sets the "title_options" field.
func (_u *ArticleUpdate) SetTitleOptions(v json.RawMessage) *ArticleUpdate {
	_u.mutation.SetTitleOptions(v)
	return _u
}

// AppendTitleOptions appends value to the "title_options" field.
func (_u *ArticleUpdate) AppendTitleOptions(v json.RawMessage) *ArticleUpdate {
	_u.mutation.AppendTitleOptions(v)
	return _u
}

// ClearTitleOptions clears the value of the "title_options" field.
func (_u *ArticleUpdate) ClearTitleOptions() *ArticleUpdate {
	_u.mutation.ClearTitleOptions()
	return _u
}

// SetOutline sets the "outline" field.
func (_u *ArticleUpdate) SetOutline(v json.RawMessage) *ArticleUpdate {
	_u.mutation.SetOutline(v)
	return _u
}

// AppendOutline appends value to the "outline" field.
func (_u *ArticleUpdate) AppendOutline(v json.RawMessage) *ArticleUpdate {
	_u.mutation.AppendOutline(v)
	return _u
}

// ClearOutline clears the value of the "outline" field.
func (_u *ArticleUpdate) ClearOutline() *ArticleUpdate {
	_u.mutation.ClearOutline()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdate) SetContent(v string) *ArticleUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableContent(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdate) ClearContent() *ArticleUpdate {
	_u.mutation.ClearContent()
	return _u
}

// SetFullContent sets the "full_content" field.
func (_u *ArticleUpdate) SetFullContent(v string) *ArticleUpdate {
	_u.mutation.SetFullContent(v)
	return _u
}

// SetNillableFullContent sets the "full_content" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableFullContent(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetFullContent(*v)
	}
	return _u
}

// ClearFullContent clears the value of the "full_content" field.
func (_u *ArticleUpdate) ClearFullContent() *ArticleUpdate {
	_u.mutation.ClearFullContent()
	return _u
}

// SetImages sets the "images" field.
func (_u *ArticleUpdate) SetImages(v json.RawMessage) *ArticleUpdate {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *ArticleUpdate) AppendImages(v json.RawMessage) *ArticleUpdate {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *ArticleUpdate) ClearImages() *ArticleUpdate {
	_u.mutation.ClearImages()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ArticleUpdate) SetStatus(v article.Status) *ArticleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableStatus(v *article.Status) *ArticleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *ArticleUpdate) SetPhase(v article.Phase) *ArticleUpdate {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillablePhase(v *article.Phase) *ArticleUpdate {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ArticleUpdate) SetErrorMessage(v string) *ArticleUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableErrorMessage(v *string) *ArticleUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ArticleUpdate) ClearErrorMessage() *ArticleUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStyle sets the "style" field.
func (_u *ArticleUpdate) SetStyle(v article.Style) *ArticleUpdate {
	_u.mutation.SetStyle(v)
	return _u
}

// SetNillableStyle sets the "style" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableStyle(v *article.Style) *ArticleUpdate {
	if v != nil {
		_u.SetStyle(*v)
	}
	return _u
}

// ClearStyle clears the value of the "style" field.
func (_u *ArticleUpdate) ClearStyle() *ArticleUpdate {
	_u.mutation.ClearStyle()
	return _u
}

// SetEnabledImageMethods sets the "enabled_image_methods" field.
func (_u *ArticleUpdate) SetEnabledImageMethods(v []string) *ArticleUpdate {
	_u.mutation.SetEnabledImageMethods(v)
	return _u
}

// AppendEnabledImageMethods appends value to the "enabled_image_methods" field.
func (_u *ArticleUpdate) AppendEnabledImageMethods(v []string) *ArticleUpdate {
	_u.mutation.AppendEnabledImageMethods(v)
	return _u
}

// ClearEnabledImageMethods clears the value of the "enabled_image_methods" field.
func (_u *ArticleUpdate) ClearEnabledImageMethods() *ArticleUpdate {
	_u.mutation.ClearEnabledImageMethods()
	return _u
}

// SetCompletedTime sets the "completed_time" field.
func (_u *ArticleUpdate) SetCompletedTime(v time.Time) *ArticleUpdate {
	_u.mutation.SetCompletedTime(v)
	return _u
}

// SetNillableCompletedTime sets the "completed_time" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableCompletedTime(v *time.Time) *ArticleUpdate {
	if v != nil {
		_u.SetCompletedTime(*v)
	}
	return _u
}

// ClearCompletedTime clears the value of the "completed_time" field.
func (_u *ArticleUpdate) ClearCompletedTime() *ArticleUpdate {
	_u.mutation.ClearCompletedTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ArticleUpdate) SetUpdateTime(v time.Time) *ArticleUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *ArticleUpdate) SetIsDelete(v bool) *ArticleUpdate {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *ArticleUpdate) SetNillableIsDelete(v *bool) *ArticleUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ArticleUpdate) SetUser(v *User) *ArticleUpdate {
	return _u.SetUserID(v.ID)
}

// AddAgentLogIDs adds the "agent_logs" edge to the AgentLog entity by IDs.
func (_u *ArticleUpdate) AddAgentLogIDs(ids ...int64) *ArticleUpdate {
	_u.mutation.AddAgentLogIDs(ids...)
	return _u
}

// AddAgentLogs adds the "agent_logs" edges to the AgentLog entity.
func (_u *ArticleUpdate) AddAgentLogs(v ...*AgentLog) *ArticleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentLogIDs(ids...)
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdate) Mutation() *ArticleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ArticleUpdate) ClearUser() *ArticleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAgentLogs clears all "agent_logs" edges to the AgentLog entity.
func (_u *ArticleUpdate) ClearAgentLogs() *ArticleUpdate {
	_u.mutation.ClearAgentLogs()
	return _u
}

// RemoveAgentLogIDs removes the "agent_logs" edge to AgentLog entities by IDs.
func (_u *ArticleUpdate) RemoveAgentLogIDs(ids ...int64) *ArticleUpdate {
	_u.mutation.RemoveAgentLogIDs(ids...)
	return _u
}

// RemoveAgentLogs removes "agent_logs" edges to AgentLog entities.
func (_u *ArticleUpdate) RemoveAgentLogs(v ...*AgentLog) *ArticleUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArticleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := article.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleUpdate) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := article.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "Article.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Topic(); ok {
		if err := article.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "Article.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := article.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Article.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := article.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Article.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Style(); ok {
		if err := article.StyleValidator(v); err != nil {
			return &ValidationError{Name: "style", err: fmt.Errorf(`ent: validator failed for field "Article.style": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Article.user"`)
	}
	return nil
}

func (_u *ArticleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(article.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(article.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserDescription(); ok {
		_spec.SetField(article.FieldUserDescription, field.TypeString, value)
	}
	if _u.mutation.UserDescriptionCleared() {
		_spec.ClearField(article.FieldUserDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MainTitle(); ok {
		_spec.SetField(article.FieldMainTitle, field.TypeString, value)
	}
	if _u.mutation.MainTitleCleared() {
		_spec.ClearField(article.FieldMainTitle, field.TypeString)
	}
	if value, ok := _u.mutation.SubTitle(); ok {
		_spec.SetField(article.FieldSubTitle, field.TypeString, value)
	}
	if _u.mutation.SubTitleCleared() {
		_spec.ClearField(article.FieldSubTitle, field.TypeString)
	}
	if value, ok := _u.mutation.TitleOptions(); ok {
		_spec.SetField(article.FieldTitleOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTitleOptions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldTitleOptions, value)
		})
	}
	if _u.mutation.TitleOptionsCleared() {
		_spec.ClearField(article.FieldTitleOptions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Outline(); ok {
		_spec.SetField(article.FieldOutline, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOutline(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldOutline, value)
		})
	}
	if _u.mutation.OutlineCleared() {
		_spec.ClearField(article.FieldOutline, field.TypeJSON)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.FullContent(); ok {
		_spec.SetField(article.FieldFullContent, field.TypeString, value)
	}
	if _u.mutation.FullContentCleared() {
		_spec.ClearField(article.FieldFullContent, field.TypeString)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(article.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(article.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(article.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(article.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(article.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(article.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Style(); ok {
		_spec.SetField(article.FieldStyle, field.TypeEnum, value)
	}
	if _u.mutation.StyleCleared() {
		_spec.ClearField(article.FieldStyle, field.TypeEnum)
	}
	if value, ok := _u.mutation.EnabledImageMethods(); ok {
		_spec.SetField(article.FieldEnabledImageMethods, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEnabledImageMethods(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldEnabledImageMethods, value)
		})
	}
	if _u.mutation.EnabledImageMethodsCleared() {
		_spec.ClearField(article.FieldEnabledImageMethods, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedTime(); ok {
		_spec.SetField(article.FieldCompletedTime, field.TypeTime, value)
	}
	if _u.mutation.CompletedTimeCleared() {
		_spec.ClearField(article.FieldCompletedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(article.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(article.FieldIsDelete, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.UserTable,
			Columns: []string{article.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.UserTable,
			Columns: []string{article.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   article.AgentLogsTable,
			Columns: []string{article.AgentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentLogsIDs(); len(nodes) > 0 && !_u.mutation.AgentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   article.AgentLogsTable,
			Columns: []string{article.AgentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   article.AgentLogsTable,
			Columns: []string{article.AgentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetTaskID sets the "task_id" field.
func (_u *ArticleUpdateOne) SetTaskID(v string) *ArticleUpdateOne {
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableTaskID(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ArticleUpdateOne) SetUserID(v int64) *ArticleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableUserID(v *int64) *ArticleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTopic sets the "topic" field.
func (_u *ArticleUpdateOne) SetTopic(v string) *ArticleUpdateOne {
	_u.mutation.SetTopic(v)
	return _u
}

// SetNillableTopic sets the "topic" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableTopic(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetTopic(*v)
	}
	return _u
}

// SetUserDescription sets the "user_description" field.
func (_u *ArticleUpdateOne) SetUserDescription(v string) *ArticleUpdateOne {
	_u.mutation.SetUserDescription(v)
	return _u
}

// SetNillableUserDescription sets the "user_description" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableUserDescription(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetUserDescription(*v)
	}
	return _u
}

// ClearUserDescription clears the value of the "user_description" field.
func (_u *ArticleUpdateOne) ClearUserDescription() *ArticleUpdateOne {
	_u.mutation.ClearUserDescription()
	return _u
}

// SetMainTitle sets the "main_title" field.
func (_u *ArticleUpdateOne) SetMainTitle(v string) *ArticleUpdateOne {
	_u.mutation.SetMainTitle(v)
	return _u
}

// SetNillableMainTitle sets the "main_title" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableMainTitle(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetMainTitle(*v)
	}
	return _u
}

// ClearMainTitle clears the value of the "main_title" field.
func (_u *ArticleUpdateOne) ClearMainTitle() *ArticleUpdateOne {
	_u.mutation.ClearMainTitle()
	return _u
}

// SetSubTitle sets the "sub_title" field.
func (_u *ArticleUpdateOne) SetSubTitle(v string) *ArticleUpdateOne {
	_u.mutation.SetSubTitle(v)
	return _u
}

// SetNillableSubTitle sets the "sub_title" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableSubTitle(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetSubTitle(*v)
	}
	return _u
}

// ClearSubTitle clears the value of the "sub_title" field.
func (_u *ArticleUpdateOne) ClearSubTitle() *ArticleUpdateOne {
	_u.mutation.ClearSubTitle()
	return _u
}

// SetTitleOptions sets the "title_options" field.
func (_u *ArticleUpdateOne) SetTitleOptions(v json.RawMessage) *ArticleUpdateOne {
	_u.mutation.SetTitleOptions(v)
	return _u
}

// AppendTitleOptions appends value to the "title_options" field.
func (_u *ArticleUpdateOne) AppendTitleOptions(v json.RawMessage) *ArticleUpdateOne {
	_u.mutation.AppendTitleOptions(v)
	return _u
}

// ClearTitleOptions clears the value of the "title_options" field.
func (_u *ArticleUpdateOne) ClearTitleOptions() *ArticleUpdateOne {
	_u.mutation.ClearTitleOptions()
	return _u
}

// SetOutline sets the "outline" field.
func (_u *ArticleUpdateOne) SetOutline(v json.RawMessage) *ArticleUpdateOne {
	_u.mutation.SetOutline(v)
	return _u
}

// AppendOutline appends value to the "outline" field.
func (_u *ArticleUpdateOne) AppendOutline(v json.RawMessage) *ArticleUpdateOne {
	_u.mutation.AppendOutline(v)
	return _u
}

// ClearOutline clears the value of the "outline" field.
func (_u *ArticleUpdateOne) ClearOutline() *ArticleUpdateOne {
	_u.mutation.ClearOutline()
	return _u
}

// SetContent sets the "content" field.
func (_u *ArticleUpdateOne) SetContent(v string) *ArticleUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableContent(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// ClearContent clears the value of the "content" field.
func (_u *ArticleUpdateOne) ClearContent() *ArticleUpdateOne {
	_u.mutation.ClearContent()
	return _u
}

// SetFullContent sets the "full_content" field.
func (_u *ArticleUpdateOne) SetFullContent(v string) *ArticleUpdateOne {
	_u.mutation.SetFullContent(v)
	return _u
}

// SetNillableFullContent sets the "full_content" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableFullContent(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetFullContent(*v)
	}
	return _u
}

// ClearFullContent clears the value of the "full_content" field.
func (_u *ArticleUpdateOne) ClearFullContent() *ArticleUpdateOne {
	_u.mutation.ClearFullContent()
	return _u
}

// SetImages sets the "images" field.
func (_u *ArticleUpdateOne) SetImages(v json.RawMessage) *ArticleUpdateOne {
	_u.mutation.SetImages(v)
	return _u
}

// AppendImages appends value to the "images" field.
func (_u *ArticleUpdateOne) AppendImages(v json.RawMessage) *ArticleUpdateOne {
	_u.mutation.AppendImages(v)
	return _u
}

// ClearImages clears the value of the "images" field.
func (_u *ArticleUpdateOne) ClearImages() *ArticleUpdateOne {
	_u.mutation.ClearImages()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ArticleUpdateOne) SetStatus(v article.Status) *ArticleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableStatus(v *article.Status) *ArticleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPhase sets the "phase" field.
func (_u *ArticleUpdateOne) SetPhase(v article.Phase) *ArticleUpdateOne {
	_u.mutation.SetPhase(v)
	return _u
}

// SetNillablePhase sets the "phase" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillablePhase(v *article.Phase) *ArticleUpdateOne {
	if v != nil {
		_u.SetPhase(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ArticleUpdateOne) SetErrorMessage(v string) *ArticleUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableErrorMessage(v *string) *ArticleUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *ArticleUpdateOne) ClearErrorMessage() *ArticleUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetStyle sets the "style" field.
func (_u *ArticleUpdateOne) SetStyle(v article.Style) *ArticleUpdateOne {
	_u.mutation.SetStyle(v)
	return _u
}

// SetNillableStyle sets the "style" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableStyle(v *article.Style) *ArticleUpdateOne {
	if v != nil {
		_u.SetStyle(*v)
	}
	return _u
}

// ClearStyle clears the value of the "style" field.
func (_u *ArticleUpdateOne) ClearStyle() *ArticleUpdateOne {
	_u.mutation.ClearStyle()
	return _u
}

// SetEnabledImageMethods sets the "enabled_image_methods" field.
func (_u *ArticleUpdateOne) SetEnabledImageMethods(v []string) *ArticleUpdateOne {
	_u.mutation.SetEnabledImageMethods(v)
	return _u
}

// AppendEnabledImageMethods appends value to the "enabled_image_methods" field.
func (_u *ArticleUpdateOne) AppendEnabledImageMethods(v []string) *ArticleUpdateOne {
	_u.mutation.AppendEnabledImageMethods(v)
	return _u
}

// ClearEnabledImageMethods clears the value of the "enabled_image_methods" field.
func (_u *ArticleUpdateOne) ClearEnabledImageMethods() *ArticleUpdateOne {
	_u.mutation.ClearEnabledImageMethods()
	return _u
}

// SetCompletedTime sets the "completed_time" field.
func (_u *ArticleUpdateOne) SetCompletedTime(v time.Time) *ArticleUpdateOne {
	_u.mutation.SetCompletedTime(v)
	return _u
}

// SetNillableCompletedTime sets the "completed_time" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableCompletedTime(v *time.Time) *ArticleUpdateOne {
	if v != nil {
		_u.SetCompletedTime(*v)
	}
	return _u
}

// ClearCompletedTime clears the value of the "completed_time" field.
func (_u *ArticleUpdateOne) ClearCompletedTime() *ArticleUpdateOne {
	_u.mutation.ClearCompletedTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ArticleUpdateOne) SetUpdateTime(v time.Time) *ArticleUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *ArticleUpdateOne) SetIsDelete(v bool) *ArticleUpdateOne {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *ArticleUpdateOne) SetNillableIsDelete(v *bool) *ArticleUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ArticleUpdateOne) SetUser(v *User) *ArticleUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddAgentLogIDs adds the "agent_logs" edge to the AgentLog entity by IDs.
func (_u *ArticleUpdateOne) AddAgentLogIDs(ids ...int64) *ArticleUpdateOne {
	_u.mutation.AddAgentLogIDs(ids...)
	return _u
}

// AddAgentLogs adds the "agent_logs" edges to the AgentLog entity.
func (_u *ArticleUpdateOne) AddAgentLogs(v ...*AgentLog) *ArticleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAgentLogIDs(ids...)
}

// Mutation returns the ArticleMutation object of the builder.
func (_u *ArticleUpdateOne) Mutation() *ArticleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ArticleUpdateOne) ClearUser() *ArticleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAgentLogs clears all "agent_logs" edges to the AgentLog entity.
func (_u *ArticleUpdateOne) ClearAgentLogs() *ArticleUpdateOne {
	_u.mutation.ClearAgentLogs()
	return _u
}

// RemoveAgentLogIDs removes the "agent_logs" edge to AgentLog entities by IDs.
func (_u *ArticleUpdateOne) RemoveAgentLogIDs(ids ...int64) *ArticleUpdateOne {
	_u.mutation.RemoveAgentLogIDs(ids...)
	return _u
}

// RemoveAgentLogs removes "agent_logs" edges to AgentLog entities.
func (_u *ArticleUpdateOne) RemoveAgentLogs(v ...*AgentLog) *ArticleUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAgentLogIDs(ids...)
}

// Where appends a list predicates to the ArticleUpdate builder.
func (_u *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Article entity.
func (_u *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ArticleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := article.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArticleUpdateOne) check() error {
	if v, ok := _u.mutation.TaskID(); ok {
		if err := article.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "Article.task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Topic(); ok {
		if err := article.TopicValidator(v); err != nil {
			return &ValidationError{Name: "topic", err: fmt.Errorf(`ent: validator failed for field "Article.topic": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := article.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Article.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phase(); ok {
		if err := article.PhaseValidator(v); err != nil {
			return &ValidationError{Name: "phase", err: fmt.Errorf(`ent: validator failed for field "Article.phase": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Style(); ok {
		if err := article.StyleValidator(v); err != nil {
			return &ValidationError{Name: "style", err: fmt.Errorf(`ent: validator failed for field "Article.style": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Article.user"`)
	}
	return nil
}

func (_u *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(article.FieldTaskID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Topic(); ok {
		_spec.SetField(article.FieldTopic, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserDescription(); ok {
		_spec.SetField(article.FieldUserDescription, field.TypeString, value)
	}
	if _u.mutation.UserDescriptionCleared() {
		_spec.ClearField(article.FieldUserDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MainTitle(); ok {
		_spec.SetField(article.FieldMainTitle, field.TypeString, value)
	}
	if _u.mutation.MainTitleCleared() {
		_spec.ClearField(article.FieldMainTitle, field.TypeString)
	}
	if value, ok := _u.mutation.SubTitle(); ok {
		_spec.SetField(article.FieldSubTitle, field.TypeString, value)
	}
	if _u.mutation.SubTitleCleared() {
		_spec.ClearField(article.FieldSubTitle, field.TypeString)
	}
	if value, ok := _u.mutation.TitleOptions(); ok {
		_spec.SetField(article.FieldTitleOptions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTitleOptions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldTitleOptions, value)
		})
	}
	if _u.mutation.TitleOptionsCleared() {
		_spec.ClearField(article.FieldTitleOptions, field.TypeJSON)
	}
	if value, ok := _u.mutation.Outline(); ok {
		_spec.SetField(article.FieldOutline, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOutline(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldOutline, value)
		})
	}
	if _u.mutation.OutlineCleared() {
		_spec.ClearField(article.FieldOutline, field.TypeJSON)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ContentCleared() {
		_spec.ClearField(article.FieldContent, field.TypeString)
	}
	if value, ok := _u.mutation.FullContent(); ok {
		_spec.SetField(article.FieldFullContent, field.TypeString, value)
	}
	if _u.mutation.FullContentCleared() {
		_spec.ClearField(article.FieldFullContent, field.TypeString)
	}
	if value, ok := _u.mutation.Images(); ok {
		_spec.SetField(article.FieldImages, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImages(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldImages, value)
		})
	}
	if _u.mutation.ImagesCleared() {
		_spec.ClearField(article.FieldImages, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(article.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Phase(); ok {
		_spec.SetField(article.FieldPhase, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(article.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(article.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Style(); ok {
		_spec.SetField(article.FieldStyle, field.TypeEnum, value)
	}
	if _u.mutation.StyleCleared() {
		_spec.ClearField(article.FieldStyle, field.TypeEnum)
	}
	if value, ok := _u.mutation.EnabledImageMethods(); ok {
		_spec.SetField(article.FieldEnabledImageMethods, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEnabledImageMethods(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, article.FieldEnabledImageMethods, value)
		})
	}
	if _u.mutation.EnabledImageMethodsCleared() {
		_spec.ClearField(article.FieldEnabledImageMethods, field.TypeJSON)
	}
	if value, ok := _u.mutation.CompletedTime(); ok {
		_spec.SetField(article.FieldCompletedTime, field.TypeTime, value)
	}
	if _u.mutation.CompletedTimeCleared() {
		_spec.ClearField(article.FieldCompletedTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(article.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(article.FieldIsDelete, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.UserTable,
			Columns: []string{article.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.UserTable,
			Columns: []string{article.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   article.AgentLogsTable,
			Columns: []string{article.AgentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAgentLogsIDs(); len(nodes) > 0 && !_u.mutation.AgentLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   article.AgentLogsTable,
			Columns: []string{article.AgentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   article.AgentLogsTable,
			Columns: []string{article.AgentLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentlog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Article{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
