// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wood-passage-creator/ent/paymentrecord"
	"wood-passage-creator/ent/predicate"
	"wood-passage-creator/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentRecordUpdate is the builder for updating PaymentRecord entities.
type PaymentRecordUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentRecordMutation
}

// Where appends a list predicates to the PaymentRecordUpdate builder.
func (_u *PaymentRecordUpdate) Where(ps ...predicate.PaymentRecord) *PaymentRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentRecordUpdate) SetUserID(v int64) *PaymentRecordUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableUserID(v *int64) *PaymentRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStripeSessionID sets the "stripe_session_id" field.
func (_u *PaymentRecordUpdate) SetStripeSessionID(v string) *PaymentRecordUpdate {
	_u.mutation.SetStripeSessionID(v)
	return _u
}

// SetNillableStripeSessionID sets the "stripe_session_id" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableStripeSessionID(v *string) *PaymentRecordUpdate {
	if v != nil {
		_u.SetStripeSessionID(*v)
	}
	return _u
}

// SetStripePaymentIntentID sets the "stripe_payment_intent_id" field.
func (_u *PaymentRecordUpdate) SetStripePaymentIntentID(v string) *PaymentRecordUpdate {
	_u.mutation.SetStripePaymentIntentID(v)
	return _u
}

// SetNillableStripePaymentIntentID sets the "stripe_payment_intent_id" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableStripePaymentIntentID(v *string) *PaymentRecordUpdate {
	if v != nil {
		_u.SetStripePaymentIntentID(*v)
	}
	return _u
}

// ClearStripePaymentIntentID clears the value of the "stripe_payment_intent_id" field.
func (_u *PaymentRecordUpdate) ClearStripePaymentIntentID() *PaymentRecordUpdate {
	_u.mutation.ClearStripePaymentIntentID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentRecordUpdate) SetAmount(v float64) *PaymentRecordUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableAmount(v *float64) *PaymentRecordUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentRecordUpdate) AddAmount(v float64) *PaymentRecordUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentRecordUpdate) SetCurrency(v string) *PaymentRecordUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableCurrency(v *string) *PaymentRecordUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentRecordUpdate) SetStatus(v paymentrecord.Status) *PaymentRecordUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableStatus(v *paymentrecord.Status) *PaymentRecordUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProductType sets the "product_type" field.
func (_u *PaymentRecordUpdate) SetProductType(v string) *PaymentRecordUpdate {
	_u.mutation.SetProductType(v)
	return _u
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableProductType(v *string) *PaymentRecordUpdate {
	if v != nil {
		_u.SetProductType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentRecordUpdate) SetDescription(v string) *PaymentRecordUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableDescription(v *string) *PaymentRecordUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentRecordUpdate) ClearDescription() *PaymentRecordUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetRefundTime sets the "refund_time" field.
func (_u *PaymentRecordUpdate) SetRefundTime(v time.Time) *PaymentRecordUpdate {
	_u.mutation.SetRefundTime(v)
	return _u
}

// SetNillableRefundTime sets the "refund_time" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableRefundTime(v *time.Time) *PaymentRecordUpdate {
	if v != nil {
		_u.SetRefundTime(*v)
	}
	return _u
}

// ClearRefundTime clears the value of the "refund_time" field.
func (_u *PaymentRecordUpdate) ClearRefundTime() *PaymentRecordUpdate {
	_u.mutation.ClearRefundTime()
	return _u
}

// SetRefundReason sets the "refund_reason" field.
func (_u *PaymentRecordUpdate) SetRefundReason(v string) *PaymentRecordUpdate {
	_u.mutation.SetRefundReason(v)
	return _u
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_u *PaymentRecordUpdate) SetNillableRefundReason(v *string) *PaymentRecordUpdate {
	if v != nil {
		_u.SetRefundReason(*v)
	}
	return _u
}

// ClearRefundReason clears the value of the "refund_reason" field.
func (_u *PaymentRecordUpdate) ClearRefundReason() *PaymentRecordUpdate {
	_u.mutation.ClearRefundReason()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *PaymentRecordUpdate) SetUpdateTime(v time.Time) *PaymentRecordUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentRecordUpdate) SetUser(v *User) *PaymentRecordUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentRecordMutation object of the builder.
func (_u *PaymentRecordUpdate) Mutation() *PaymentRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentRecordUpdate) ClearUser() *PaymentRecordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := paymentrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentRecordUpdate) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := paymentrecord.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeSessionID(); ok {
		if err := paymentrecord.StripeSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_session_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.stripe_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripePaymentIntentID(); ok {
		if err := paymentrecord.StripePaymentIntentIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_payment_intent_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.stripe_payment_intent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentrecord.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductType(); ok {
		if err := paymentrecord.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.product_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := paymentrecord.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundReason(); ok {
		if err := paymentrecord.RefundReasonValidator(v); err != nil {
			return &ValidationError{Name: "refund_reason", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.refund_reason": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentRecord.user"`)
	}
	return nil
}

func (_u *PaymentRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentrecord.Table, paymentrecord.Columns, sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StripeSessionID(); ok {
		_spec.SetField(paymentrecord.FieldStripeSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripePaymentIntentID(); ok {
		_spec.SetField(paymentrecord.FieldStripePaymentIntentID, field.TypeString, value)
	}
	if _u.mutation.StripePaymentIntentIDCleared() {
		_spec.ClearField(paymentrecord.FieldStripePaymentIntentID, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentrecord.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentrecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProductType(); ok {
		_spec.SetField(paymentrecord.FieldProductType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentrecord.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentrecord.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RefundTime(); ok {
		_spec.SetField(paymentrecord.FieldRefundTime, field.TypeTime, value)
	}
	if _u.mutation.RefundTimeCleared() {
		_spec.ClearField(paymentrecord.FieldRefundTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundReason(); ok {
		_spec.SetField(paymentrecord.FieldRefundReason, field.TypeString, value)
	}
	if _u.mutation.RefundReasonCleared() {
		_spec.ClearField(paymentrecord.FieldRefundReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(paymentrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentrecord.UserTable,
			Columns: []string{paymentrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentrecord.UserTable,
			Columns: []string{paymentrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentRecordUpdateOne is the builder for updating a single PaymentRecord entity.
type PaymentRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentRecordMutation
}

// SetUserID sets the "user_id" field.
func (_u *PaymentRecordUpdateOne) SetUserID(v int64) *PaymentRecordUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableUserID(v *int64) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStripeSessionID sets the "stripe_session_id" field.
func (_u *PaymentRecordUpdateOne) SetStripeSessionID(v string) *PaymentRecordUpdateOne {
	_u.mutation.SetStripeSessionID(v)
	return _u
}

// SetNillableStripeSessionID sets the "stripe_session_id" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableStripeSessionID(v *string) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetStripeSessionID(*v)
	}
	return _u
}

// SetStripePaymentIntentID sets the "stripe_payment_intent_id" field.
func (_u *PaymentRecordUpdateOne) SetStripePaymentIntentID(v string) *PaymentRecordUpdateOne {
	_u.mutation.SetStripePaymentIntentID(v)
	return _u
}

// SetNillableStripePaymentIntentID sets the "stripe_payment_intent_id" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableStripePaymentIntentID(v *string) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetStripePaymentIntentID(*v)
	}
	return _u
}

// ClearStripePaymentIntentID clears the value of the "stripe_payment_intent_id" field.
func (_u *PaymentRecordUpdateOne) ClearStripePaymentIntentID() *PaymentRecordUpdateOne {
	_u.mutation.ClearStripePaymentIntentID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentRecordUpdateOne) SetAmount(v float64) *PaymentRecordUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableAmount(v *float64) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentRecordUpdateOne) AddAmount(v float64) *PaymentRecordUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentRecordUpdateOne) SetCurrency(v string) *PaymentRecordUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableCurrency(v *string) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentRecordUpdateOne) SetStatus(v paymentrecord.Status) *PaymentRecordUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableStatus(v *paymentrecord.Status) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProductType sets the "product_type" field.
func (_u *PaymentRecordUpdateOne) SetProductType(v string) *PaymentRecordUpdateOne {
	_u.mutation.SetProductType(v)
	return _u
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableProductType(v *string) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetProductType(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentRecordUpdateOne) SetDescription(v string) *PaymentRecordUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableDescription(v *string) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentRecordUpdateOne) ClearDescription() *PaymentRecordUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetRefundTime sets the "refund_time" field.
func (_u *PaymentRecordUpdateOne) SetRefundTime(v time.Time) *PaymentRecordUpdateOne {
	_u.mutation.SetRefundTime(v)
	return _u
}

// SetNillableRefundTime sets the "refund_time" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableRefundTime(v *time.Time) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetRefundTime(*v)
	}
	return _u
}

// ClearRefundTime clears the value of the "refund_time" field.
func (_u *PaymentRecordUpdateOne) ClearRefundTime() *PaymentRecordUpdateOne {
	_u.mutation.ClearRefundTime()
	return _u
}

// SetRefundReason sets the "refund_reason" field.
func (_u *PaymentRecordUpdateOne) SetRefundReason(v string) *PaymentRecordUpdateOne {
	_u.mutation.SetRefundReason(v)
	return _u
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_u *PaymentRecordUpdateOne) SetNillableRefundReason(v *string) *PaymentRecordUpdateOne {
	if v != nil {
		_u.SetRefundReason(*v)
	}
	return _u
}

// ClearRefundReason clears the value of the "refund_reason" field.
func (_u *PaymentRecordUpdateOne) ClearRefundReason() *PaymentRecordUpdateOne {
	_u.mutation.ClearRefundReason()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *PaymentRecordUpdateOne) SetUpdateTime(v time.Time) *PaymentRecordUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentRecordUpdateOne) SetUser(v *User) *PaymentRecordUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentRecordMutation object of the builder.
func (_u *PaymentRecordUpdateOne) Mutation() *PaymentRecordMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentRecordUpdateOne) ClearUser() *PaymentRecordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentRecordUpdate builder.
func (_u *PaymentRecordUpdateOne) Where(ps ...predicate.PaymentRecord) *PaymentRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentRecordUpdateOne) Select(field string, fields ...string) *PaymentRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentRecord entity.
func (_u *PaymentRecordUpdateOne) Save(ctx context.Context) (*PaymentRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentRecordUpdateOne) SaveX(ctx context.Context) *PaymentRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := paymentrecord.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentRecordUpdateOne) check() error {
	if v, ok := _u.mutation.UserID(); ok {
		if err := paymentrecord.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripeSessionID(); ok {
		if err := paymentrecord.StripeSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_session_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.stripe_session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StripePaymentIntentID(); ok {
		if err := paymentrecord.StripePaymentIntentIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_payment_intent_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.stripe_payment_intent_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentrecord.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductType(); ok {
		if err := paymentrecord.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.product_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := paymentrecord.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundReason(); ok {
		if err := paymentrecord.RefundReasonValidator(v); err != nil {
			return &ValidationError{Name: "refund_reason", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.refund_reason": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentRecord.user"`)
	}
	return nil
}

func (_u *PaymentRecordUpdateOne) sqlSave(ctx context.Context) (_node *PaymentRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentrecord.Table, paymentrecord.Columns, sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentrecord.FieldID)
		for _, f := range fields {
			if !paymentrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StripeSessionID(); ok {
		_spec.SetField(paymentrecord.FieldStripeSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.StripePaymentIntentID(); ok {
		_spec.SetField(paymentrecord.FieldStripePaymentIntentID, field.TypeString, value)
	}
	if _u.mutation.StripePaymentIntentIDCleared() {
		_spec.ClearField(paymentrecord.FieldStripePaymentIntentID, field.TypeString)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentrecord.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentrecord.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentrecord.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ProductType(); ok {
		_spec.SetField(paymentrecord.FieldProductType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentrecord.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentrecord.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.RefundTime(); ok {
		_spec.SetField(paymentrecord.FieldRefundTime, field.TypeTime, value)
	}
	if _u.mutation.RefundTimeCleared() {
		_spec.ClearField(paymentrecord.FieldRefundTime, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundReason(); ok {
		_spec.SetField(paymentrecord.FieldRefundReason, field.TypeString, value)
	}
	if _u.mutation.RefundReasonCleared() {
		_spec.ClearField(paymentrecord.FieldRefundReason, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(paymentrecord.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentrecord.UserTable,
			Columns: []string{paymentrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentrecord.UserTable,
			Columns: []string{paymentrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
