// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"projecttemp/ent/paymentrecord"
	"projecttemp/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PaymentRecordCreate is the builder for creating a PaymentRecord entity.
type PaymentRecordCreate struct {
	config
	mutation *PaymentRecordMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PaymentRecordCreate) SetUserID(v int64) *PaymentRecordCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStripeSessionID sets the "stripe_session_id" field.
func (_c *PaymentRecordCreate) SetStripeSessionID(v string) *PaymentRecordCreate {
	_c.mutation.SetStripeSessionID(v)
	return _c
}

// SetStripePaymentIntentID sets the "stripe_payment_intent_id" field.
func (_c *PaymentRecordCreate) SetStripePaymentIntentID(v string) *PaymentRecordCreate {
	_c.mutation.SetStripePaymentIntentID(v)
	return _c
}

// SetNillableStripePaymentIntentID sets the "stripe_payment_intent_id" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableStripePaymentIntentID(v *string) *PaymentRecordCreate {
	if v != nil {
		_c.SetStripePaymentIntentID(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentRecordCreate) SetAmount(v float64) *PaymentRecordCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentRecordCreate) SetCurrency(v string) *PaymentRecordCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableCurrency(v *string) *PaymentRecordCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentRecordCreate) SetStatus(v paymentrecord.Status) *PaymentRecordCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableStatus(v *paymentrecord.Status) *PaymentRecordCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProductType sets the "product_type" field.
func (_c *PaymentRecordCreate) SetProductType(v string) *PaymentRecordCreate {
	_c.mutation.SetProductType(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PaymentRecordCreate) SetDescription(v string) *PaymentRecordCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableDescription(v *string) *PaymentRecordCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetRefundTime sets the "refund_time" field.
func (_c *PaymentRecordCreate) SetRefundTime(v time.Time) *PaymentRecordCreate {
	_c.mutation.SetRefundTime(v)
	return _c
}

// SetNillableRefundTime sets the "refund_time" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableRefundTime(v *time.Time) *PaymentRecordCreate {
	if v != nil {
		_c.SetRefundTime(*v)
	}
	return _c
}

// SetRefundReason sets the "refund_reason" field.
func (_c *PaymentRecordCreate) SetRefundReason(v string) *PaymentRecordCreate {
	_c.mutation.SetRefundReason(v)
	return _c
}

// SetNillableRefundReason sets the "refund_reason" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableRefundReason(v *string) *PaymentRecordCreate {
	if v != nil {
		_c.SetRefundReason(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *PaymentRecordCreate) SetCreateTime(v time.Time) *PaymentRecordCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableCreateTime(v *time.Time) *PaymentRecordCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *PaymentRecordCreate) SetUpdateTime(v time.Time) *PaymentRecordCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *PaymentRecordCreate) SetNillableUpdateTime(v *time.Time) *PaymentRecordCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentRecordCreate) SetID(v int64) *PaymentRecordCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentRecordCreate) SetUser(v *User) *PaymentRecordCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentRecordMutation object of the builder.
func (_c *PaymentRecordCreate) Mutation() *PaymentRecordMutation {
	return _c.mutation
}

// Save creates the PaymentRecord in the database.
func (_c *PaymentRecordCreate) Save(ctx context.Context) (*PaymentRecord, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentRecordCreate) SaveX(ctx context.Context) *PaymentRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentRecordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentRecordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentRecordCreate) defaults() {
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymentrecord.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentrecord.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := paymentrecord.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := paymentrecord.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentRecordCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentRecord.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := paymentrecord.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StripeSessionID(); !ok {
		return &ValidationError{Name: "stripe_session_id", err: errors.New(`ent: missing required field "PaymentRecord.stripe_session_id"`)}
	}
	if v, ok := _c.mutation.StripeSessionID(); ok {
		if err := paymentrecord.StripeSessionIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_session_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.stripe_session_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.StripePaymentIntentID(); ok {
		if err := paymentrecord.StripePaymentIntentIDValidator(v); err != nil {
			return &ValidationError{Name: "stripe_payment_intent_id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.stripe_payment_intent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentRecord.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentRecord.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := paymentrecord.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentRecord.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentrecord.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductType(); !ok {
		return &ValidationError{Name: "product_type", err: errors.New(`ent: missing required field "PaymentRecord.product_type"`)}
	}
	if v, ok := _c.mutation.ProductType(); ok {
		if err := paymentrecord.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.product_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := paymentrecord.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.description": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RefundReason(); ok {
		if err := paymentrecord.RefundReasonValidator(v); err != nil {
			return &ValidationError{Name: "refund_reason", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.refund_reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "PaymentRecord.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "PaymentRecord.update_time"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := paymentrecord.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "PaymentRecord.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentRecord.user"`)}
	}
	return nil
}

func (_c *PaymentRecordCreate) sqlSave(ctx context.Context) (*PaymentRecord, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentRecordCreate) createSpec() (*PaymentRecord, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentRecord{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentrecord.Table, sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.StripeSessionID(); ok {
		_spec.SetField(paymentrecord.FieldStripeSessionID, field.TypeString, value)
		_node.StripeSessionID = value
	}
	if value, ok := _c.mutation.StripePaymentIntentID(); ok {
		_spec.SetField(paymentrecord.FieldStripePaymentIntentID, field.TypeString, value)
		_node.StripePaymentIntentID = &value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(paymentrecord.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymentrecord.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentrecord.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ProductType(); ok {
		_spec.SetField(paymentrecord.FieldProductType, field.TypeString, value)
		_node.ProductType = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(paymentrecord.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.RefundTime(); ok {
		_spec.SetField(paymentrecord.FieldRefundTime, field.TypeTime, value)
		_node.RefundTime = &value
	}
	if value, ok := _c.mutation.RefundReason(); ok {
		_spec.SetField(paymentrecord.FieldRefundReason, field.TypeString, value)
		_node.RefundReason = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(paymentrecord.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(paymentrecord.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentrecord.UserTable,
			Columns: []string{paymentrecord.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentRecordCreateBulk is the builder for creating many PaymentRecord entities in bulk.
type PaymentRecordCreateBulk struct {
	config
	err      error
	builders []*PaymentRecordCreate
}

// Save creates the PaymentRecord entities in the database.
func (_c *PaymentRecordCreateBulk) Save(ctx context.Context) ([]*PaymentRecord, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentRecord, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentRecordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentRecordCreateBulk) SaveX(ctx context.Context) []*PaymentRecord {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentRecordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentRecordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
