// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"wood-passage-creator/ent/paymentrecord"
	"wood-passage-creator/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PaymentRecord is the model entity for the PaymentRecord schema.
type PaymentRecord struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID int64 `json:"id,omitempty"`
	// 所属用户 ID（FK → users.id）
	UserID int64 `json:"user_id,omitempty"`
	// Stripe Checkout Session ID
	StripeSessionID string `json:"stripe_session_id,omitempty"`
	// Stripe PaymentIntent ID
	StripePaymentIntentID *string `json:"stripe_payment_intent_id,omitempty"`
	// 支付金额
	Amount float64 `json:"amount,omitempty"`
	// 币种
	Currency string `json:"currency,omitempty"`
	// 支付状态：PENDING/SUCCEEDED/FAILED/REFUNDED
	Status paymentrecord.Status `json:"status,omitempty"`
	// 产品类型，如 VIP_PERMANENT
	ProductType string `json:"product_type,omitempty"`
	// 描述
	Description *string `json:"description,omitempty"`
	// 退款时间
	RefundTime *time.Time `json:"refund_time,omitempty"`
	// 退款原因
	RefundReason *string `json:"refund_reason,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PaymentRecordQuery when eager-loading is set.
	Edges        PaymentRecordEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PaymentRecordEdges holds the relations/edges for other nodes in the graph.
type PaymentRecordEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PaymentRecordEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PaymentRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case paymentrecord.FieldAmount:
			values[i] = new(sql.NullFloat64)
		case paymentrecord.FieldID, paymentrecord.FieldUserID:
			values[i] = new(sql.NullInt64)
		case paymentrecord.FieldStripeSessionID, paymentrecord.FieldStripePaymentIntentID, paymentrecord.FieldCurrency, paymentrecord.FieldStatus, paymentrecord.FieldProductType, paymentrecord.FieldDescription, paymentrecord.FieldRefundReason:
			values[i] = new(sql.NullString)
		case paymentrecord.FieldRefundTime, paymentrecord.FieldCreateTime, paymentrecord.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PaymentRecord fields.
func (_m *PaymentRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case paymentrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case paymentrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case paymentrecord.FieldStripeSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_session_id", values[i])
			} else if value.Valid {
				_m.StripeSessionID = value.String
			}
		case paymentrecord.FieldStripePaymentIntentID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field stripe_payment_intent_id", values[i])
			} else if value.Valid {
				_m.StripePaymentIntentID = new(string)
				*_m.StripePaymentIntentID = value.String
			}
		case paymentrecord.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case paymentrecord.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case paymentrecord.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = paymentrecord.Status(value.String)
			}
		case paymentrecord.FieldProductType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = value.String
			}
		case paymentrecord.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case paymentrecord.FieldRefundTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refund_time", values[i])
			} else if value.Valid {
				_m.RefundTime = new(time.Time)
				*_m.RefundTime = value.Time
			}
		case paymentrecord.FieldRefundReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_reason", values[i])
			} else if value.Valid {
				_m.RefundReason = new(string)
				*_m.RefundReason = value.String
			}
		case paymentrecord.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case paymentrecord.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PaymentRecord.
// This includes values selected through modifiers, order, etc.
func (_m *PaymentRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PaymentRecord entity.
func (_m *PaymentRecord) QueryUser() *UserQuery {
	return NewPaymentRecordClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PaymentRecord.
// Note that you need to call PaymentRecord.Unwrap() before calling this method if this PaymentRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PaymentRecord) Update() *PaymentRecordUpdateOne {
	return NewPaymentRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PaymentRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PaymentRecord) Unwrap() *PaymentRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PaymentRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PaymentRecord) String() string {
	var builder strings.Builder
	builder.WriteString("PaymentRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("stripe_session_id=")
	builder.WriteString(_m.StripeSessionID)
	builder.WriteString(", ")
	if v := _m.StripePaymentIntentID; v != nil {
		builder.WriteString("stripe_payment_intent_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(_m.ProductType)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RefundTime; v != nil {
		builder.WriteString("refund_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundReason; v != nil {
		builder.WriteString("refund_reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PaymentRecords is a parsable slice of PaymentRecord.
type PaymentRecords []*PaymentRecord
