// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"projecttemp/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	// 主键
	ID int64 `json:"id,omitempty"`
	// 登录账号，唯一
	UserAccount string `json:"user_account,omitempty"`
	// 密码哈希，非明文
	UserPassword string `json:"-"`
	// 用户昵称
	UserName *string `json:"user_name,omitempty"`
	// 用户头像 URL
	UserAvatar *string `json:"user_avatar,omitempty"`
	// 用户简介
	UserProfile *string `json:"user_profile,omitempty"`
	// 用户角色：user/admin/vip
	UserRole user.UserRole `json:"user_role,omitempty"`
	// 剩余配额
	Quota int `json:"quota,omitempty"`
	// 成为会员时间
	VipTime *time.Time `json:"vip_time,omitempty"`
	// 编辑时间
	EditTime time.Time `json:"edit_time,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime time.Time `json:"update_time,omitempty"`
	// 是否删除（软删除）
	IsDelete bool `json:"is_delete,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Articles holds the value of the articles edge.
	Articles []*Article `json:"articles,omitempty"`
	// PaymentRecords holds the value of the payment_records edge.
	PaymentRecords []*PaymentRecord `json:"payment_records,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ArticlesOrErr returns the Articles value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ArticlesOrErr() ([]*Article, error) {
	if e.loadedTypes[0] {
		return e.Articles, nil
	}
	return nil, &NotLoadedError{edge: "articles"}
}

// PaymentRecordsOrErr returns the PaymentRecords value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PaymentRecordsOrErr() ([]*PaymentRecord, error) {
	if e.loadedTypes[1] {
		return e.PaymentRecords, nil
	}
	return nil, &NotLoadedError{edge: "payment_records"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldIsDelete:
			values[i] = new(sql.NullBool)
		case user.FieldID, user.FieldQuota:
			values[i] = new(sql.NullInt64)
		case user.FieldUserAccount, user.FieldUserPassword, user.FieldUserName, user.FieldUserAvatar, user.FieldUserProfile, user.FieldUserRole:
			values[i] = new(sql.NullString)
		case user.FieldVipTime, user.FieldEditTime, user.FieldCreateTime, user.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case user.FieldUserAccount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_account", values[i])
			} else if value.Valid {
				_m.UserAccount = value.String
			}
		case user.FieldUserPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_password", values[i])
			} else if value.Valid {
				_m.UserPassword = value.String
			}
		case user.FieldUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_name", values[i])
			} else if value.Valid {
				_m.UserName = new(string)
				*_m.UserName = value.String
			}
		case user.FieldUserAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_avatar", values[i])
			} else if value.Valid {
				_m.UserAvatar = new(string)
				*_m.UserAvatar = value.String
			}
		case user.FieldUserProfile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_profile", values[i])
			} else if value.Valid {
				_m.UserProfile = new(string)
				*_m.UserProfile = value.String
			}
		case user.FieldUserRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_role", values[i])
			} else if value.Valid {
				_m.UserRole = user.UserRole(value.String)
			}
		case user.FieldQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quota", values[i])
			} else if value.Valid {
				_m.Quota = int(value.Int64)
			}
		case user.FieldVipTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field vip_time", values[i])
			} else if value.Valid {
				_m.VipTime = new(time.Time)
				*_m.VipTime = value.Time
			}
		case user.FieldEditTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field edit_time", values[i])
			} else if value.Valid {
				_m.EditTime = value.Time
			}
		case user.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = value.Time
			}
		case user.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = value.Time
			}
		case user.FieldIsDelete:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_delete", values[i])
			} else if value.Valid {
				_m.IsDelete = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryArticles queries the "articles" edge of the User entity.
func (_m *User) QueryArticles() *ArticleQuery {
	return NewUserClient(_m.config).QueryArticles(_m)
}

// QueryPaymentRecords queries the "payment_records" edge of the User entity.
func (_m *User) QueryPaymentRecords() *PaymentRecordQuery {
	return NewUserClient(_m.config).QueryPaymentRecords(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_account=")
	builder.WriteString(_m.UserAccount)
	builder.WriteString(", ")
	builder.WriteString("user_password=<sensitive>")
	builder.WriteString(", ")
	if v := _m.UserName; v != nil {
		builder.WriteString("user_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserAvatar; v != nil {
		builder.WriteString("user_avatar=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.UserProfile; v != nil {
		builder.WriteString("user_profile=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("user_role=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserRole))
	builder.WriteString(", ")
	builder.WriteString("quota=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quota))
	builder.WriteString(", ")
	if v := _m.VipTime; v != nil {
		builder.WriteString("vip_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("edit_time=")
	builder.WriteString(_m.EditTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("create_time=")
	builder.WriteString(_m.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(_m.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_delete=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDelete))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
