// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"projecttemp/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUserAccount sets the "user_account" field.
func (_c *UserCreate) SetUserAccount(v string) *UserCreate {
	_c.mutation.SetUserAccount(v)
	return _c
}

// SetUserPassword sets the "user_password" field.
func (_c *UserCreate) SetUserPassword(v string) *UserCreate {
	_c.mutation.SetUserPassword(v)
	return _c
}

// SetUserName sets the "user_name" field.
func (_c *UserCreate) SetUserName(v string) *UserCreate {
	_c.mutation.SetUserName(v)
	return _c
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_c *UserCreate) SetNillableUserName(v *string) *UserCreate {
	if v != nil {
		_c.SetUserName(*v)
	}
	return _c
}

// SetUserAvatar sets the "user_avatar" field.
func (_c *UserCreate) SetUserAvatar(v string) *UserCreate {
	_c.mutation.SetUserAvatar(v)
	return _c
}

// SetNillableUserAvatar sets the "user_avatar" field if the given value is not nil.
func (_c *UserCreate) SetNillableUserAvatar(v *string) *UserCreate {
	if v != nil {
		_c.SetUserAvatar(*v)
	}
	return _c
}

// SetUserProfile sets the "user_profile" field.
func (_c *UserCreate) SetUserProfile(v string) *UserCreate {
	_c.mutation.SetUserProfile(v)
	return _c
}

// SetNillableUserProfile sets the "user_profile" field if the given value is not nil.
func (_c *UserCreate) SetNillableUserProfile(v *string) *UserCreate {
	if v != nil {
		_c.SetUserProfile(*v)
	}
	return _c
}

// SetUserRole sets the "user_role" field.
func (_c *UserCreate) SetUserRole(v user.UserRole) *UserCreate {
	_c.mutation.SetUserRole(v)
	return _c
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_c *UserCreate) SetNillableUserRole(v *user.UserRole) *UserCreate {
	if v != nil {
		_c.SetUserRole(*v)
	}
	return _c
}

// SetQuota sets the "quota" field.
func (_c *UserCreate) SetQuota(v int) *UserCreate {
	_c.mutation.SetQuota(v)
	return _c
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_c *UserCreate) SetNillableQuota(v *int) *UserCreate {
	if v != nil {
		_c.SetQuota(*v)
	}
	return _c
}

// SetVipTime sets the "vip_time" field.
func (_c *UserCreate) SetVipTime(v time.Time) *UserCreate {
	_c.mutation.SetVipTime(v)
	return _c
}

// SetNillableVipTime sets the "vip_time" field if the given value is not nil.
func (_c *UserCreate) SetNillableVipTime(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetVipTime(*v)
	}
	return _c
}

// SetEditTime sets the "edit_time" field.
func (_c *UserCreate) SetEditTime(v time.Time) *UserCreate {
	_c.mutation.SetEditTime(v)
	return _c
}

// SetNillableEditTime sets the "edit_time" field if the given value is not nil.
func (_c *UserCreate) SetNillableEditTime(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetEditTime(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *UserCreate) SetCreateTime(v time.Time) *UserCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreateTime(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *UserCreate) SetUpdateTime(v time.Time) *UserCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdateTime(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "is_delete" field.
func (_c *UserCreate) SetIsDelete(v bool) *UserCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsDelete(v *bool) *UserCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v int64) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.UserRole(); !ok {
		v := user.DefaultUserRole
		_c.mutation.SetUserRole(v)
	}
	if _, ok := _c.mutation.Quota(); !ok {
		v := user.DefaultQuota
		_c.mutation.SetQuota(v)
	}
	if _, ok := _c.mutation.EditTime(); !ok {
		v := user.DefaultEditTime()
		_c.mutation.SetEditTime(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := user.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := user.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := user.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if _, ok := _c.mutation.UserAccount(); !ok {
		return &ValidationError{Name: "user_account", err: errors.New(`ent: missing required field "User.user_account"`)}
	}
	if v, ok := _c.mutation.UserAccount(); ok {
		if err := user.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "User.user_account": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserPassword(); !ok {
		return &ValidationError{Name: "user_password", err: errors.New(`ent: missing required field "User.user_password"`)}
	}
	if v, ok := _c.mutation.UserPassword(); ok {
		if err := user.UserPasswordValidator(v); err != nil {
			return &ValidationError{Name: "user_password", err: fmt.Errorf(`ent: validator failed for field "User.user_password": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserName(); ok {
		if err := user.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "User.user_name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserAvatar(); ok {
		if err := user.UserAvatarValidator(v); err != nil {
			return &ValidationError{Name: "user_avatar", err: fmt.Errorf(`ent: validator failed for field "User.user_avatar": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UserProfile(); ok {
		if err := user.UserProfileValidator(v); err != nil {
			return &ValidationError{Name: "user_profile", err: fmt.Errorf(`ent: validator failed for field "User.user_profile": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserRole(); !ok {
		return &ValidationError{Name: "user_role", err: errors.New(`ent: missing required field "User.user_role"`)}
	}
	if v, ok := _c.mutation.UserRole(); ok {
		if err := user.UserRoleValidator(v); err != nil {
			return &ValidationError{Name: "user_role", err: fmt.Errorf(`ent: validator failed for field "User.user_role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quota(); !ok {
		return &ValidationError{Name: "quota", err: errors.New(`ent: missing required field "User.quota"`)}
	}
	if v, ok := _c.mutation.Quota(); ok {
		if err := user.QuotaValidator(v); err != nil {
			return &ValidationError{Name: "quota", err: fmt.Errorf(`ent: validator failed for field "User.quota": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EditTime(); !ok {
		return &ValidationError{Name: "edit_time", err: errors.New(`ent: missing required field "User.edit_time"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "User.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "User.update_time"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "is_delete", err: errors.New(`ent: missing required field "User.is_delete"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := user.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "User.id": %w`, err)}
		}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserAccount(); ok {
		_spec.SetField(user.FieldUserAccount, field.TypeString, value)
		_node.UserAccount = value
	}
	if value, ok := _c.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
		_node.UserPassword = value
	}
	if value, ok := _c.mutation.UserName(); ok {
		_spec.SetField(user.FieldUserName, field.TypeString, value)
		_node.UserName = &value
	}
	if value, ok := _c.mutation.UserAvatar(); ok {
		_spec.SetField(user.FieldUserAvatar, field.TypeString, value)
		_node.UserAvatar = &value
	}
	if value, ok := _c.mutation.UserProfile(); ok {
		_spec.SetField(user.FieldUserProfile, field.TypeString, value)
		_node.UserProfile = &value
	}
	if value, ok := _c.mutation.UserRole(); ok {
		_spec.SetField(user.FieldUserRole, field.TypeEnum, value)
		_node.UserRole = value
	}
	if value, ok := _c.mutation.Quota(); ok {
		_spec.SetField(user.FieldQuota, field.TypeInt, value)
		_node.Quota = value
	}
	if value, ok := _c.mutation.VipTime(); ok {
		_spec.SetField(user.FieldVipTime, field.TypeTime, value)
		_node.VipTime = &value
	}
	if value, ok := _c.mutation.EditTime(); ok {
		_spec.SetField(user.FieldEditTime, field.TypeTime, value)
		_node.EditTime = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(user.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeBool, value)
		_node.IsDelete = value
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
