// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wood-passage-creator/ent/article"
	"wood-passage-creator/ent/paymentrecord"
	"wood-passage-creator/ent/predicate"
	"wood-passage-creator/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserAccount sets the "user_account" field.
func (_u *UserUpdate) SetUserAccount(v string) *UserUpdate {
	_u.mutation.SetUserAccount(v)
	return _u
}

// SetNillableUserAccount sets the "user_account" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserAccount(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserAccount(*v)
	}
	return _u
}

// SetUserPassword sets the "user_password" field.
func (_u *UserUpdate) SetUserPassword(v string) *UserUpdate {
	_u.mutation.SetUserPassword(v)
	return _u
}

// SetNillableUserPassword sets the "user_password" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserPassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserPassword(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *UserUpdate) SetUserName(v string) *UserUpdate {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserName(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *UserUpdate) ClearUserName() *UserUpdate {
	_u.mutation.ClearUserName()
	return _u
}

// SetUserAvatar sets the "user_avatar" field.
func (_u *UserUpdate) SetUserAvatar(v string) *UserUpdate {
	_u.mutation.SetUserAvatar(v)
	return _u
}

// SetNillableUserAvatar sets the "user_avatar" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserAvatar(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserAvatar(*v)
	}
	return _u
}

// ClearUserAvatar clears the value of the "user_avatar" field.
func (_u *UserUpdate) ClearUserAvatar() *UserUpdate {
	_u.mutation.ClearUserAvatar()
	return _u
}

// SetUserProfile sets the "user_profile" field.
func (_u *UserUpdate) SetUserProfile(v string) *UserUpdate {
	_u.mutation.SetUserProfile(v)
	return _u
}

// SetNillableUserProfile sets the "user_profile" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserProfile(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserProfile(*v)
	}
	return _u
}

// ClearUserProfile clears the value of the "user_profile" field.
func (_u *UserUpdate) ClearUserProfile() *UserUpdate {
	_u.mutation.ClearUserProfile()
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *UserUpdate) SetUserRole(v user.UserRole) *UserUpdate {
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserRole(v *user.UserRole) *UserUpdate {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// SetQuota sets the "quota" field.
func (_u *UserUpdate) SetQuota(v int) *UserUpdate {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *UserUpdate) SetNillableQuota(v *int) *UserUpdate {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *UserUpdate) AddQuota(v int) *UserUpdate {
	_u.mutation.AddQuota(v)
	return _u
}

// SetVipTime sets the "vip_time" field.
func (_u *UserUpdate) SetVipTime(v time.Time) *UserUpdate {
	_u.mutation.SetVipTime(v)
	return _u
}

// SetNillableVipTime sets the "vip_time" field if the given value is not nil.
func (_u *UserUpdate) SetNillableVipTime(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetVipTime(*v)
	}
	return _u
}

// ClearVipTime clears the value of the "vip_time" field.
func (_u *UserUpdate) ClearVipTime() *UserUpdate {
	_u.mutation.ClearVipTime()
	return _u
}

// SetEditTime sets the "edit_time" field.
func (_u *UserUpdate) SetEditTime(v time.Time) *UserUpdate {
	_u.mutation.SetEditTime(v)
	return _u
}

// SetNillableEditTime sets the "edit_time" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEditTime(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetEditTime(*v)
	}
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdate) SetUpdateTime(v time.Time) *UserUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *UserUpdate) SetIsDelete(v bool) *UserUpdate {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsDelete(v *bool) *UserUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddArticleIDs adds the "articles" edge to the Article entity by IDs.
func (_u *UserUpdate) AddArticleIDs(ids ...int64) *UserUpdate {
	_u.mutation.AddArticleIDs(ids...)
	return _u
}

// AddArticles adds the "articles" edges to the Article entity.
func (_u *UserUpdate) AddArticles(v ...*Article) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArticleIDs(ids...)
}

// AddPaymentRecordIDs adds the "payment_records" edge to the PaymentRecord entity by IDs.
func (_u *UserUpdate) AddPaymentRecordIDs(ids ...int64) *UserUpdate {
	_u.mutation.AddPaymentRecordIDs(ids...)
	return _u
}

// AddPaymentRecords adds the "payment_records" edges to the PaymentRecord entity.
func (_u *UserUpdate) AddPaymentRecords(v ...*PaymentRecord) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentRecordIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// ClearArticles clears all "articles" edges to the Article entity.
func (_u *UserUpdate) ClearArticles() *UserUpdate {
	_u.mutation.ClearArticles()
	return _u
}

// RemoveArticleIDs removes the "articles" edge to Article entities by IDs.
func (_u *UserUpdate) RemoveArticleIDs(ids ...int64) *UserUpdate {
	_u.mutation.RemoveArticleIDs(ids...)
	return _u
}

// RemoveArticles removes "articles" edges to Article entities.
func (_u *UserUpdate) RemoveArticles(v ...*Article) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArticleIDs(ids...)
}

// ClearPaymentRecords clears all "payment_records" edges to the PaymentRecord entity.
func (_u *UserUpdate) ClearPaymentRecords() *UserUpdate {
	_u.mutation.ClearPaymentRecords()
	return _u
}

// RemovePaymentRecordIDs removes the "payment_records" edge to PaymentRecord entities by IDs.
func (_u *UserUpdate) RemovePaymentRecordIDs(ids ...int64) *UserUpdate {
	_u.mutation.RemovePaymentRecordIDs(ids...)
	return _u
}

// RemovePaymentRecords removes "payment_records" edges to PaymentRecord entities.
func (_u *UserUpdate) RemovePaymentRecords(v ...*PaymentRecord) *UserUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentRecordIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.UserAccount(); ok {
		if err := user.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "User.user_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserPassword(); ok {
		if err := user.UserPasswordValidator(v); err != nil {
			return &ValidationError{Name: "user_password", err: fmt.Errorf(`ent: validator failed for field "User.user_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := user.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "User.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAvatar(); ok {
		if err := user.UserAvatarValidator(v); err != nil {
			return &ValidationError{Name: "user_avatar", err: fmt.Errorf(`ent: validator failed for field "User.user_avatar": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserProfile(); ok {
		if err := user.UserProfileValidator(v); err != nil {
			return &ValidationError{Name: "user_profile", err: fmt.Errorf(`ent: validator failed for field "User.user_profile": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserRole(); ok {
		if err := user.UserRoleValidator(v); err != nil {
			return &ValidationError{Name: "user_role", err: fmt.Errorf(`ent: validator failed for field "User.user_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quota(); ok {
		if err := user.QuotaValidator(v); err != nil {
			return &ValidationError{Name: "quota", err: fmt.Errorf(`ent: validator failed for field "User.quota": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAccount(); ok {
		_spec.SetField(user.FieldUserAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(user.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(user.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.UserAvatar(); ok {
		_spec.SetField(user.FieldUserAvatar, field.TypeString, value)
	}
	if _u.mutation.UserAvatarCleared() {
		_spec.ClearField(user.FieldUserAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.UserProfile(); ok {
		_spec.SetField(user.FieldUserProfile, field.TypeString, value)
	}
	if _u.mutation.UserProfileCleared() {
		_spec.ClearField(user.FieldUserProfile, field.TypeString)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(user.FieldUserRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(user.FieldQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(user.FieldQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VipTime(); ok {
		_spec.SetField(user.FieldVipTime, field.TypeTime, value)
	}
	if _u.mutation.VipTimeCleared() {
		_spec.ClearField(user.FieldVipTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EditTime(); ok {
		_spec.SetField(user.FieldEditTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeBool, value)
	}
	if _u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArticlesTable,
			Columns: []string{user.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArticlesIDs(); len(nodes) > 0 && !_u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArticlesTable,
			Columns: []string{user.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArticlesTable,
			Columns: []string{user.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentRecordsTable,
			Columns: []string{user.PaymentRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentRecordsIDs(); len(nodes) > 0 && !_u.mutation.PaymentRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentRecordsTable,
			Columns: []string{user.PaymentRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentRecordsTable,
			Columns: []string{user.PaymentRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUserAccount sets the "user_account" field.
func (_u *UserUpdateOne) SetUserAccount(v string) *UserUpdateOne {
	_u.mutation.SetUserAccount(v)
	return _u
}

// SetNillableUserAccount sets the "user_account" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserAccount(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserAccount(*v)
	}
	return _u
}

// SetUserPassword sets the "user_password" field.
func (_u *UserUpdateOne) SetUserPassword(v string) *UserUpdateOne {
	_u.mutation.SetUserPassword(v)
	return _u
}

// SetNillableUserPassword sets the "user_password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserPassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserPassword(*v)
	}
	return _u
}

// SetUserName sets the "user_name" field.
func (_u *UserUpdateOne) SetUserName(v string) *UserUpdateOne {
	_u.mutation.SetUserName(v)
	return _u
}

// SetNillableUserName sets the "user_name" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserName(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserName(*v)
	}
	return _u
}

// ClearUserName clears the value of the "user_name" field.
func (_u *UserUpdateOne) ClearUserName() *UserUpdateOne {
	_u.mutation.ClearUserName()
	return _u
}

// SetUserAvatar sets the "user_avatar" field.
func (_u *UserUpdateOne) SetUserAvatar(v string) *UserUpdateOne {
	_u.mutation.SetUserAvatar(v)
	return _u
}

// SetNillableUserAvatar sets the "user_avatar" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserAvatar(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserAvatar(*v)
	}
	return _u
}

// ClearUserAvatar clears the value of the "user_avatar" field.
func (_u *UserUpdateOne) ClearUserAvatar() *UserUpdateOne {
	_u.mutation.ClearUserAvatar()
	return _u
}

// SetUserProfile sets the "user_profile" field.
func (_u *UserUpdateOne) SetUserProfile(v string) *UserUpdateOne {
	_u.mutation.SetUserProfile(v)
	return _u
}

// SetNillableUserProfile sets the "user_profile" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserProfile(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserProfile(*v)
	}
	return _u
}

// ClearUserProfile clears the value of the "user_profile" field.
func (_u *UserUpdateOne) ClearUserProfile() *UserUpdateOne {
	_u.mutation.ClearUserProfile()
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *UserUpdateOne) SetUserRole(v user.UserRole) *UserUpdateOne {
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserRole(v *user.UserRole) *UserUpdateOne {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// SetQuota sets the "quota" field.
func (_u *UserUpdateOne) SetQuota(v int) *UserUpdateOne {
	_u.mutation.ResetQuota()
	_u.mutation.SetQuota(v)
	return _u
}

// SetNillableQuota sets the "quota" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableQuota(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetQuota(*v)
	}
	return _u
}

// AddQuota adds value to the "quota" field.
func (_u *UserUpdateOne) AddQuota(v int) *UserUpdateOne {
	_u.mutation.AddQuota(v)
	return _u
}

// SetVipTime sets the "vip_time" field.
func (_u *UserUpdateOne) SetVipTime(v time.Time) *UserUpdateOne {
	_u.mutation.SetVipTime(v)
	return _u
}

// SetNillableVipTime sets the "vip_time" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableVipTime(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetVipTime(*v)
	}
	return _u
}

// ClearVipTime clears the value of the "vip_time" field.
func (_u *UserUpdateOne) ClearVipTime() *UserUpdateOne {
	_u.mutation.ClearVipTime()
	return _u
}

// SetEditTime sets the "edit_time" field.
func (_u *UserUpdateOne) SetEditTime(v time.Time) *UserUpdateOne {
	_u.mutation.SetEditTime(v)
	return _u
}

// SetNillableEditTime sets the "edit_time" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEditTime(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetEditTime(*v)
	}
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdateOne) SetUpdateTime(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *UserUpdateOne) SetIsDelete(v bool) *UserUpdateOne {
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsDelete(v *bool) *UserUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddArticleIDs adds the "articles" edge to the Article entity by IDs.
func (_u *UserUpdateOne) AddArticleIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.AddArticleIDs(ids...)
	return _u
}

// AddArticles adds the "articles" edges to the Article entity.
func (_u *UserUpdateOne) AddArticles(v ...*Article) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddArticleIDs(ids...)
}

// AddPaymentRecordIDs adds the "payment_records" edge to the PaymentRecord entity by IDs.
func (_u *UserUpdateOne) AddPaymentRecordIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.AddPaymentRecordIDs(ids...)
	return _u
}

// AddPaymentRecords adds the "payment_records" edges to the PaymentRecord entity.
func (_u *UserUpdateOne) AddPaymentRecords(v ...*PaymentRecord) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPaymentRecordIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// ClearArticles clears all "articles" edges to the Article entity.
func (_u *UserUpdateOne) ClearArticles() *UserUpdateOne {
	_u.mutation.ClearArticles()
	return _u
}

// RemoveArticleIDs removes the "articles" edge to Article entities by IDs.
func (_u *UserUpdateOne) RemoveArticleIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.RemoveArticleIDs(ids...)
	return _u
}

// RemoveArticles removes "articles" edges to Article entities.
func (_u *UserUpdateOne) RemoveArticles(v ...*Article) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveArticleIDs(ids...)
}

// ClearPaymentRecords clears all "payment_records" edges to the PaymentRecord entity.
func (_u *UserUpdateOne) ClearPaymentRecords() *UserUpdateOne {
	_u.mutation.ClearPaymentRecords()
	return _u
}

// RemovePaymentRecordIDs removes the "payment_records" edge to PaymentRecord entities by IDs.
func (_u *UserUpdateOne) RemovePaymentRecordIDs(ids ...int64) *UserUpdateOne {
	_u.mutation.RemovePaymentRecordIDs(ids...)
	return _u
}

// RemovePaymentRecords removes "payment_records" edges to PaymentRecord entities.
func (_u *UserUpdateOne) RemovePaymentRecords(v ...*PaymentRecord) *UserUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePaymentRecordIDs(ids...)
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.UserAccount(); ok {
		if err := user.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "User.user_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserPassword(); ok {
		if err := user.UserPasswordValidator(v); err != nil {
			return &ValidationError{Name: "user_password", err: fmt.Errorf(`ent: validator failed for field "User.user_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserName(); ok {
		if err := user.UserNameValidator(v); err != nil {
			return &ValidationError{Name: "user_name", err: fmt.Errorf(`ent: validator failed for field "User.user_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAvatar(); ok {
		if err := user.UserAvatarValidator(v); err != nil {
			return &ValidationError{Name: "user_avatar", err: fmt.Errorf(`ent: validator failed for field "User.user_avatar": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserProfile(); ok {
		if err := user.UserProfileValidator(v); err != nil {
			return &ValidationError{Name: "user_profile", err: fmt.Errorf(`ent: validator failed for field "User.user_profile": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserRole(); ok {
		if err := user.UserRoleValidator(v); err != nil {
			return &ValidationError{Name: "user_role", err: fmt.Errorf(`ent: validator failed for field "User.user_role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Quota(); ok {
		if err := user.QuotaValidator(v); err != nil {
			return &ValidationError{Name: "quota", err: fmt.Errorf(`ent: validator failed for field "User.quota": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAccount(); ok {
		_spec.SetField(user.FieldUserAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserName(); ok {
		_spec.SetField(user.FieldUserName, field.TypeString, value)
	}
	if _u.mutation.UserNameCleared() {
		_spec.ClearField(user.FieldUserName, field.TypeString)
	}
	if value, ok := _u.mutation.UserAvatar(); ok {
		_spec.SetField(user.FieldUserAvatar, field.TypeString, value)
	}
	if _u.mutation.UserAvatarCleared() {
		_spec.ClearField(user.FieldUserAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.UserProfile(); ok {
		_spec.SetField(user.FieldUserProfile, field.TypeString, value)
	}
	if _u.mutation.UserProfileCleared() {
		_spec.ClearField(user.FieldUserProfile, field.TypeString)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(user.FieldUserRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Quota(); ok {
		_spec.SetField(user.FieldQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuota(); ok {
		_spec.AddField(user.FieldQuota, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VipTime(); ok {
		_spec.SetField(user.FieldVipTime, field.TypeTime, value)
	}
	if _u.mutation.VipTimeCleared() {
		_spec.ClearField(user.FieldVipTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EditTime(); ok {
		_spec.SetField(user.FieldEditTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeBool, value)
	}
	if _u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArticlesTable,
			Columns: []string{user.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedArticlesIDs(); len(nodes) > 0 && !_u.mutation.ArticlesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArticlesTable,
			Columns: []string{user.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArticlesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ArticlesTable,
			Columns: []string{user.ArticlesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PaymentRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentRecordsTable,
			Columns: []string{user.PaymentRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPaymentRecordsIDs(); len(nodes) > 0 && !_u.mutation.PaymentRecordsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentRecordsTable,
			Columns: []string{user.PaymentRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PaymentRecordsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.PaymentRecordsTable,
			Columns: []string{user.PaymentRecordsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentrecord.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
