// Code generated by ent, DO NOT EDIT.

package article

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the article type in the database.
	Label = "article"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTopic holds the string denoting the topic field in the database.
	FieldTopic = "topic"
	// FieldUserDescription holds the string denoting the user_description field in the database.
	FieldUserDescription = "user_description"
	// FieldMainTitle holds the string denoting the main_title field in the database.
	FieldMainTitle = "main_title"
	// FieldSubTitle holds the string denoting the sub_title field in the database.
	FieldSubTitle = "sub_title"
	// FieldTitleOptions holds the string denoting the title_options field in the database.
	FieldTitleOptions = "title_options"
	// FieldOutline holds the string denoting the outline field in the database.
	FieldOutline = "outline"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldFullContent holds the string denoting the full_content field in the database.
	FieldFullContent = "full_content"
	// FieldImages holds the string denoting the images field in the database.
	FieldImages = "images"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPhase holds the string denoting the phase field in the database.
	FieldPhase = "phase"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldStyle holds the string denoting the style field in the database.
	FieldStyle = "style"
	// FieldEnabledImageMethods holds the string denoting the enabled_image_methods field in the database.
	FieldEnabledImageMethods = "enabled_image_methods"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldCompletedTime holds the string denoting the completed_time field in the database.
	FieldCompletedTime = "completed_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldIsDelete holds the string denoting the is_delete field in the database.
	FieldIsDelete = "is_delete"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAgentLogs holds the string denoting the agent_logs edge name in mutations.
	EdgeAgentLogs = "agent_logs"
	// Table holds the table name of the article in the database.
	Table = "articles"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "articles"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// AgentLogsTable is the table that holds the agent_logs relation/edge.
	AgentLogsTable = "agent_logs"
	// AgentLogsInverseTable is the table name for the AgentLog entity.
	// It exists in this package in order to avoid circular dependency with the "agentlog" package.
	AgentLogsInverseTable = "agent_logs"
	// AgentLogsColumn is the table column denoting the agent_logs relation/edge.
	AgentLogsColumn = "article_id"
)

// Columns holds all SQL columns for article fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldUserID,
	FieldTopic,
	FieldUserDescription,
	FieldMainTitle,
	FieldSubTitle,
	FieldTitleOptions,
	FieldOutline,
	FieldContent,
	FieldFullContent,
	FieldImages,
	FieldStatus,
	FieldPhase,
	FieldErrorMessage,
	FieldStyle,
	FieldEnabledImageMethods,
	FieldCreateTime,
	FieldCompletedTime,
	FieldUpdateTime,
	FieldIsDelete,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	TaskIDValidator func(string) error
	// TopicValidator is a validator for the "topic" field. It is called by the builders before save.
	TopicValidator func(string) error
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultIsDelete holds the default value on creation for the "is_delete" field.
	DefaultIsDelete bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusPENDING    Status = "PENDING"
	StatusPROCESSING Status = "PROCESSING"
	StatusCOMPLETED  Status = "COMPLETED"
	StatusFAILED     Status = "FAILED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPENDING, StatusPROCESSING, StatusCOMPLETED, StatusFAILED:
		return nil
	default:
		return fmt.Errorf("article: invalid enum value for status field: %q", s)
	}
}

// Phase defines the type for the "phase" enum field.
type Phase string

// PhasePENDING is the default value of the Phase enum.
const DefaultPhase = PhasePENDING

// Phase values.
const (
	PhasePENDING            Phase = "PENDING"
	PhaseTITLE_GENERATING   Phase = "TITLE_GENERATING"
	PhaseTITLE_SELECTING    Phase = "TITLE_SELECTING"
	PhaseOUTLINE_GENERATING Phase = "OUTLINE_GENERATING"
	PhaseOUTLINE_EDITING    Phase = "OUTLINE_EDITING"
	PhaseCONTENT_GENERATING Phase = "CONTENT_GENERATING"
)

func (ph Phase) String() string {
	return string(ph)
}

// PhaseValidator is a validator for the "phase" field enum values. It is called by the builders before save.
func PhaseValidator(ph Phase) error {
	switch ph {
	case PhasePENDING, PhaseTITLE_GENERATING, PhaseTITLE_SELECTING, PhaseOUTLINE_GENERATING, PhaseOUTLINE_EDITING, PhaseCONTENT_GENERATING:
		return nil
	default:
		return fmt.Errorf("article: invalid enum value for phase field: %q", ph)
	}
}

// Style defines the type for the "style" enum field.
type Style string

// Style values.
const (
	StyleTech        Style = "tech"
	StyleEmotional   Style = "emotional"
	StyleEducational Style = "educational"
	StyleHumorous    Style = "humorous"
)

func (s Style) String() string {
	return string(s)
}

// StyleValidator is a validator for the "style" field enum values. It is called by the builders before save.
func StyleValidator(s Style) error {
	switch s {
	case StyleTech, StyleEmotional, StyleEducational, StyleHumorous:
		return nil
	default:
		return fmt.Errorf("article: invalid enum value for style field: %q", s)
	}
}

// OrderOption defines the ordering options for the Article queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByTopic orders the results by the topic field.
func ByTopic(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTopic, opts...).ToFunc()
}

// ByUserDescription orders the results by the user_description field.
func ByUserDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserDescription, opts...).ToFunc()
}

// ByMainTitle orders the results by the main_title field.
func ByMainTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMainTitle, opts...).ToFunc()
}

// BySubTitle orders the results by the sub_title field.
func BySubTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByFullContent orders the results by the full_content field.
func ByFullContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullContent, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPhase orders the results by the phase field.
func ByPhase(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhase, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByStyle orders the results by the style field.
func ByStyle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStyle, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByCompletedTime orders the results by the completed_time field.
func ByCompletedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletedTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByIsDelete orders the results by the is_delete field.
func ByIsDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDelete, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAgentLogsCount orders the results by agent_logs count.
func ByAgentLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAgentLogsStep(), opts...)
	}
}

// ByAgentLogs orders the results by agent_logs terms.
func ByAgentLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAgentLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAgentLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AgentLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AgentLogsTable, AgentLogsColumn),
	)
}
