// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserAccount holds the string denoting the user_account field in the database.
	FieldUserAccount = "user_account"
	// FieldUserPassword holds the string denoting the user_password field in the database.
	FieldUserPassword = "user_password"
	// FieldUserName holds the string denoting the user_name field in the database.
	FieldUserName = "user_name"
	// FieldUserAvatar holds the string denoting the user_avatar field in the database.
	FieldUserAvatar = "user_avatar"
	// FieldUserProfile holds the string denoting the user_profile field in the database.
	FieldUserProfile = "user_profile"
	// FieldUserRole holds the string denoting the user_role field in the database.
	FieldUserRole = "user_role"
	// FieldQuota holds the string denoting the quota field in the database.
	FieldQuota = "quota"
	// FieldVipTime holds the string denoting the vip_time field in the database.
	FieldVipTime = "vip_time"
	// FieldEditTime holds the string denoting the edit_time field in the database.
	FieldEditTime = "edit_time"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldIsDelete holds the string denoting the is_delete field in the database.
	FieldIsDelete = "is_delete"
	// EdgeArticles holds the string denoting the articles edge name in mutations.
	EdgeArticles = "articles"
	// EdgePaymentRecords holds the string denoting the payment_records edge name in mutations.
	EdgePaymentRecords = "payment_records"
	// Table holds the table name of the user in the database.
	Table = "users"
	// ArticlesTable is the table that holds the articles relation/edge.
	ArticlesTable = "articles"
	// ArticlesInverseTable is the table name for the Article entity.
	// It exists in this package in order to avoid circular dependency with the "article" package.
	ArticlesInverseTable = "articles"
	// ArticlesColumn is the table column denoting the articles relation/edge.
	ArticlesColumn = "user_id"
	// PaymentRecordsTable is the table that holds the payment_records relation/edge.
	PaymentRecordsTable = "payment_records"
	// PaymentRecordsInverseTable is the table name for the PaymentRecord entity.
	// It exists in this package in order to avoid circular dependency with the "paymentrecord" package.
	PaymentRecordsInverseTable = "payment_records"
	// PaymentRecordsColumn is the table column denoting the payment_records relation/edge.
	PaymentRecordsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUserAccount,
	FieldUserPassword,
	FieldUserName,
	FieldUserAvatar,
	FieldUserProfile,
	FieldUserRole,
	FieldQuota,
	FieldVipTime,
	FieldEditTime,
	FieldCreateTime,
	FieldUpdateTime,
	FieldIsDelete,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserAccountValidator is a validator for the "user_account" field. It is called by the builders before save.
	UserAccountValidator func(string) error
	// UserPasswordValidator is a validator for the "user_password" field. It is called by the builders before save.
	UserPasswordValidator func(string) error
	// UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	UserNameValidator func(string) error
	// UserAvatarValidator is a validator for the "user_avatar" field. It is called by the builders before save.
	UserAvatarValidator func(string) error
	// UserProfileValidator is a validator for the "user_profile" field. It is called by the builders before save.
	UserProfileValidator func(string) error
	// DefaultQuota holds the default value on creation for the "quota" field.
	DefaultQuota int
	// QuotaValidator is a validator for the "quota" field. It is called by the builders before save.
	QuotaValidator func(int) error
	// DefaultEditTime holds the default value on creation for the "edit_time" field.
	DefaultEditTime func() time.Time
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultIsDelete holds the default value on creation for the "is_delete" field.
	DefaultIsDelete bool
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// UserRole defines the type for the "user_role" enum field.
type UserRole string

// UserRoleUser is the default value of the UserRole enum.
const DefaultUserRole = UserRoleUser

// UserRole values.
const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
	UserRoleVip   UserRole = "vip"
)

func (ur UserRole) String() string {
	return string(ur)
}

// UserRoleValidator is a validator for the "user_role" field enum values. It is called by the builders before save.
func UserRoleValidator(ur UserRole) error {
	switch ur {
	case UserRoleUser, UserRoleAdmin, UserRoleVip:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for user_role field: %q", ur)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserAccount orders the results by the user_account field.
func ByUserAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAccount, opts...).ToFunc()
}

// ByUserPassword orders the results by the user_password field.
func ByUserPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserPassword, opts...).ToFunc()
}

// ByUserName orders the results by the user_name field.
func ByUserName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserName, opts...).ToFunc()
}

// ByUserAvatar orders the results by the user_avatar field.
func ByUserAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAvatar, opts...).ToFunc()
}

// ByUserProfile orders the results by the user_profile field.
func ByUserProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserProfile, opts...).ToFunc()
}

// ByUserRole orders the results by the user_role field.
func ByUserRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserRole, opts...).ToFunc()
}

// ByQuota orders the results by the quota field.
func ByQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuota, opts...).ToFunc()
}

// ByVipTime orders the results by the vip_time field.
func ByVipTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVipTime, opts...).ToFunc()
}

// ByEditTime orders the results by the edit_time field.
func ByEditTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEditTime, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByIsDelete orders the results by the is_delete field.
func ByIsDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDelete, opts...).ToFunc()
}

// ByArticlesCount orders the results by articles count.
func ByArticlesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newArticlesStep(), opts...)
	}
}

// ByArticles orders the results by articles terms.
func ByArticles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newArticlesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPaymentRecordsCount orders the results by payment_records count.
func ByPaymentRecordsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPaymentRecordsStep(), opts...)
	}
}

// ByPaymentRecords orders the results by payment_records terms.
func ByPaymentRecords(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPaymentRecordsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newArticlesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ArticlesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ArticlesTable, ArticlesColumn),
	)
}
func newPaymentRecordsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PaymentRecordsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PaymentRecordsTable, PaymentRecordsColumn),
	)
}
