// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"
	"wood-passage-creator/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// UserAccount applies equality check predicate on the "user_account" field. It's identical to UserAccountEQ.
func UserAccount(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserAccount, v))
}

// UserPassword applies equality check predicate on the "user_password" field. It's identical to UserPasswordEQ.
func UserPassword(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserPassword, v))
}

// UserName applies equality check predicate on the "user_name" field. It's identical to UserNameEQ.
func UserName(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserName, v))
}

// UserAvatar applies equality check predicate on the "user_avatar" field. It's identical to UserAvatarEQ.
func UserAvatar(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserAvatar, v))
}

// UserProfile applies equality check predicate on the "user_profile" field. It's identical to UserProfileEQ.
func UserProfile(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserProfile, v))
}

// Quota applies equality check predicate on the "quota" field. It's identical to QuotaEQ.
func Quota(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldQuota, v))
}

// VipTime applies equality check predicate on the "vip_time" field. It's identical to VipTimeEQ.
func VipTime(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVipTime, v))
}

// EditTime applies equality check predicate on the "edit_time" field. It's identical to EditTimeEQ.
func EditTime(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEditTime, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdateTime, v))
}

// IsDelete applies equality check predicate on the "is_delete" field. It's identical to IsDeleteEQ.
func IsDelete(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsDelete, v))
}

// UserAccountEQ applies the EQ predicate on the "user_account" field.
func UserAccountEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserAccount, v))
}

// UserAccountNEQ applies the NEQ predicate on the "user_account" field.
func UserAccountNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserAccount, v))
}

// UserAccountIn applies the In predicate on the "user_account" field.
func UserAccountIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserAccount, vs...))
}

// UserAccountNotIn applies the NotIn predicate on the "user_account" field.
func UserAccountNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserAccount, vs...))
}

// UserAccountGT applies the GT predicate on the "user_account" field.
func UserAccountGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserAccount, v))
}

// UserAccountGTE applies the GTE predicate on the "user_account" field.
func UserAccountGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserAccount, v))
}

// UserAccountLT applies the LT predicate on the "user_account" field.
func UserAccountLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserAccount, v))
}

// UserAccountLTE applies the LTE predicate on the "user_account" field.
func UserAccountLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserAccount, v))
}

// UserAccountContains applies the Contains predicate on the "user_account" field.
func UserAccountContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserAccount, v))
}

// UserAccountHasPrefix applies the HasPrefix predicate on the "user_account" field.
func UserAccountHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserAccount, v))
}

// UserAccountHasSuffix applies the HasSuffix predicate on the "user_account" field.
func UserAccountHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserAccount, v))
}

// UserAccountEqualFold applies the EqualFold predicate on the "user_account" field.
func UserAccountEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserAccount, v))
}

// UserAccountContainsFold applies the ContainsFold predicate on the "user_account" field.
func UserAccountContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserAccount, v))
}

// UserPasswordEQ applies the EQ predicate on the "user_password" field.
func UserPasswordEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserPassword, v))
}

// UserPasswordNEQ applies the NEQ predicate on the "user_password" field.
func UserPasswordNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserPassword, v))
}

// UserPasswordIn applies the In predicate on the "user_password" field.
func UserPasswordIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserPassword, vs...))
}

// UserPasswordNotIn applies the NotIn predicate on the "user_password" field.
func UserPasswordNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserPassword, vs...))
}

// UserPasswordGT applies the GT predicate on the "user_password" field.
func UserPasswordGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserPassword, v))
}

// UserPasswordGTE applies the GTE predicate on the "user_password" field.
func UserPasswordGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserPassword, v))
}

// UserPasswordLT applies the LT predicate on the "user_password" field.
func UserPasswordLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserPassword, v))
}

// UserPasswordLTE applies the LTE predicate on the "user_password" field.
func UserPasswordLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserPassword, v))
}

// UserPasswordContains applies the Contains predicate on the "user_password" field.
func UserPasswordContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserPassword, v))
}

// UserPasswordHasPrefix applies the HasPrefix predicate on the "user_password" field.
func UserPasswordHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserPassword, v))
}

// UserPasswordHasSuffix applies the HasSuffix predicate on the "user_password" field.
func UserPasswordHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserPassword, v))
}

// UserPasswordEqualFold applies the EqualFold predicate on the "user_password" field.
func UserPasswordEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserPassword, v))
}

// UserPasswordContainsFold applies the ContainsFold predicate on the "user_password" field.
func UserPasswordContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserPassword, v))
}

// UserNameEQ applies the EQ predicate on the "user_name" field.
func UserNameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserName, v))
}

// UserNameNEQ applies the NEQ predicate on the "user_name" field.
func UserNameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserName, v))
}

// UserNameIn applies the In predicate on the "user_name" field.
func UserNameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserName, vs...))
}

// UserNameNotIn applies the NotIn predicate on the "user_name" field.
func UserNameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserName, vs...))
}

// UserNameGT applies the GT predicate on the "user_name" field.
func UserNameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserName, v))
}

// UserNameGTE applies the GTE predicate on the "user_name" field.
func UserNameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserName, v))
}

// UserNameLT applies the LT predicate on the "user_name" field.
func UserNameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserName, v))
}

// UserNameLTE applies the LTE predicate on the "user_name" field.
func UserNameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserName, v))
}

// UserNameContains applies the Contains predicate on the "user_name" field.
func UserNameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserName, v))
}

// UserNameHasPrefix applies the HasPrefix predicate on the "user_name" field.
func UserNameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserName, v))
}

// UserNameHasSuffix applies the HasSuffix predicate on the "user_name" field.
func UserNameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserName, v))
}

// UserNameIsNil applies the IsNil predicate on the "user_name" field.
func UserNameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUserName))
}

// UserNameNotNil applies the NotNil predicate on the "user_name" field.
func UserNameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUserName))
}

// UserNameEqualFold applies the EqualFold predicate on the "user_name" field.
func UserNameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserName, v))
}

// UserNameContainsFold applies the ContainsFold predicate on the "user_name" field.
func UserNameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserName, v))
}

// UserAvatarEQ applies the EQ predicate on the "user_avatar" field.
func UserAvatarEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserAvatar, v))
}

// UserAvatarNEQ applies the NEQ predicate on the "user_avatar" field.
func UserAvatarNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserAvatar, v))
}

// UserAvatarIn applies the In predicate on the "user_avatar" field.
func UserAvatarIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserAvatar, vs...))
}

// UserAvatarNotIn applies the NotIn predicate on the "user_avatar" field.
func UserAvatarNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserAvatar, vs...))
}

// UserAvatarGT applies the GT predicate on the "user_avatar" field.
func UserAvatarGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserAvatar, v))
}

// UserAvatarGTE applies the GTE predicate on the "user_avatar" field.
func UserAvatarGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserAvatar, v))
}

// UserAvatarLT applies the LT predicate on the "user_avatar" field.
func UserAvatarLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserAvatar, v))
}

// UserAvatarLTE applies the LTE predicate on the "user_avatar" field.
func UserAvatarLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserAvatar, v))
}

// UserAvatarContains applies the Contains predicate on the "user_avatar" field.
func UserAvatarContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserAvatar, v))
}

// UserAvatarHasPrefix applies the HasPrefix predicate on the "user_avatar" field.
func UserAvatarHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserAvatar, v))
}

// UserAvatarHasSuffix applies the HasSuffix predicate on the "user_avatar" field.
func UserAvatarHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserAvatar, v))
}

// UserAvatarIsNil applies the IsNil predicate on the "user_avatar" field.
func UserAvatarIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUserAvatar))
}

// UserAvatarNotNil applies the NotNil predicate on the "user_avatar" field.
func UserAvatarNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUserAvatar))
}

// UserAvatarEqualFold applies the EqualFold predicate on the "user_avatar" field.
func UserAvatarEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserAvatar, v))
}

// UserAvatarContainsFold applies the ContainsFold predicate on the "user_avatar" field.
func UserAvatarContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserAvatar, v))
}

// UserProfileEQ applies the EQ predicate on the "user_profile" field.
func UserProfileEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserProfile, v))
}

// UserProfileNEQ applies the NEQ predicate on the "user_profile" field.
func UserProfileNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserProfile, v))
}

// UserProfileIn applies the In predicate on the "user_profile" field.
func UserProfileIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserProfile, vs...))
}

// UserProfileNotIn applies the NotIn predicate on the "user_profile" field.
func UserProfileNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserProfile, vs...))
}

// UserProfileGT applies the GT predicate on the "user_profile" field.
func UserProfileGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserProfile, v))
}

// UserProfileGTE applies the GTE predicate on the "user_profile" field.
func UserProfileGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserProfile, v))
}

// UserProfileLT applies the LT predicate on the "user_profile" field.
func UserProfileLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserProfile, v))
}

// UserProfileLTE applies the LTE predicate on the "user_profile" field.
func UserProfileLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserProfile, v))
}

// UserProfileContains applies the Contains predicate on the "user_profile" field.
func UserProfileContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserProfile, v))
}

// UserProfileHasPrefix applies the HasPrefix predicate on the "user_profile" field.
func UserProfileHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserProfile, v))
}

// UserProfileHasSuffix applies the HasSuffix predicate on the "user_profile" field.
func UserProfileHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserProfile, v))
}

// UserProfileIsNil applies the IsNil predicate on the "user_profile" field.
func UserProfileIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUserProfile))
}

// UserProfileNotNil applies the NotNil predicate on the "user_profile" field.
func UserProfileNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUserProfile))
}

// UserProfileEqualFold applies the EqualFold predicate on the "user_profile" field.
func UserProfileEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserProfile, v))
}

// UserProfileContainsFold applies the ContainsFold predicate on the "user_profile" field.
func UserProfileContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserProfile, v))
}

// UserRoleEQ applies the EQ predicate on the "user_role" field.
func UserRoleEQ(v UserRole) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserRole, v))
}

// UserRoleNEQ applies the NEQ predicate on the "user_role" field.
func UserRoleNEQ(v UserRole) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserRole, v))
}

// UserRoleIn applies the In predicate on the "user_role" field.
func UserRoleIn(vs ...UserRole) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserRole, vs...))
}

// UserRoleNotIn applies the NotIn predicate on the "user_role" field.
func UserRoleNotIn(vs ...UserRole) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserRole, vs...))
}

// QuotaEQ applies the EQ predicate on the "quota" field.
func QuotaEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldQuota, v))
}

// QuotaNEQ applies the NEQ predicate on the "quota" field.
func QuotaNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldQuota, v))
}

// QuotaIn applies the In predicate on the "quota" field.
func QuotaIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldQuota, vs...))
}

// QuotaNotIn applies the NotIn predicate on the "quota" field.
func QuotaNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldQuota, vs...))
}

// QuotaGT applies the GT predicate on the "quota" field.
func QuotaGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldQuota, v))
}

// QuotaGTE applies the GTE predicate on the "quota" field.
func QuotaGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldQuota, v))
}

// QuotaLT applies the LT predicate on the "quota" field.
func QuotaLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldQuota, v))
}

// QuotaLTE applies the LTE predicate on the "quota" field.
func QuotaLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldQuota, v))
}

// VipTimeEQ applies the EQ predicate on the "vip_time" field.
func VipTimeEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldVipTime, v))
}

// VipTimeNEQ applies the NEQ predicate on the "vip_time" field.
func VipTimeNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldVipTime, v))
}

// VipTimeIn applies the In predicate on the "vip_time" field.
func VipTimeIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldVipTime, vs...))
}

// VipTimeNotIn applies the NotIn predicate on the "vip_time" field.
func VipTimeNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldVipTime, vs...))
}

// VipTimeGT applies the GT predicate on the "vip_time" field.
func VipTimeGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldVipTime, v))
}

// VipTimeGTE applies the GTE predicate on the "vip_time" field.
func VipTimeGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldVipTime, v))
}

// VipTimeLT applies the LT predicate on the "vip_time" field.
func VipTimeLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldVipTime, v))
}

// VipTimeLTE applies the LTE predicate on the "vip_time" field.
func VipTimeLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldVipTime, v))
}

// VipTimeIsNil applies the IsNil predicate on the "vip_time" field.
func VipTimeIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldVipTime))
}

// VipTimeNotNil applies the NotNil predicate on the "vip_time" field.
func VipTimeNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldVipTime))
}

// EditTimeEQ applies the EQ predicate on the "edit_time" field.
func EditTimeEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEditTime, v))
}

// EditTimeNEQ applies the NEQ predicate on the "edit_time" field.
func EditTimeNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEditTime, v))
}

// EditTimeIn applies the In predicate on the "edit_time" field.
func EditTimeIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldEditTime, vs...))
}

// EditTimeNotIn applies the NotIn predicate on the "edit_time" field.
func EditTimeNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEditTime, vs...))
}

// EditTimeGT applies the GT predicate on the "edit_time" field.
func EditTimeGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldEditTime, v))
}

// EditTimeGTE applies the GTE predicate on the "edit_time" field.
func EditTimeGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEditTime, v))
}

// EditTimeLT applies the LT predicate on the "edit_time" field.
func EditTimeLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldEditTime, v))
}

// EditTimeLTE applies the LTE predicate on the "edit_time" field.
func EditTimeLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEditTime, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdateTime, v))
}

// IsDeleteEQ applies the EQ predicate on the "is_delete" field.
func IsDeleteEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsDelete, v))
}

// IsDeleteNEQ applies the NEQ predicate on the "is_delete" field.
func IsDeleteNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsDelete, v))
}

// HasArticles applies the HasEdge predicate on the "articles" edge.
func HasArticles() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ArticlesTable, ArticlesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArticlesWith applies the HasEdge predicate on the "articles" edge with a given conditions (other predicates).
func HasArticlesWith(preds ...predicate.Article) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newArticlesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentRecords applies the HasEdge predicate on the "payment_records" edge.
func HasPaymentRecords() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentRecordsTable, PaymentRecordsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentRecordsWith applies the HasEdge predicate on the "payment_records" edge with a given conditions (other predicates).
func HasPaymentRecordsWith(preds ...predicate.PaymentRecord) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newPaymentRecordsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
